-- Schema dump for @gdgjp/accounts
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE chapters (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('gdg', 'gdgoc')),
  created_at  INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "user" (
  "id"            TEXT NOT NULL PRIMARY KEY,
  "name"          TEXT NOT NULL,
  "email"         TEXT NOT NULL UNIQUE,
  "emailVerified" INTEGER NOT NULL,
  "image"         TEXT,
  "createdAt"     TEXT NOT NULL,
  "updatedAt"     TEXT NOT NULL,
  "isAdmin"       INTEGER
);
CREATE TABLE IF NOT EXISTS "session" (
  "id"        TEXT NOT NULL PRIMARY KEY,
  "expiresAt" TEXT NOT NULL,
  "token"     TEXT NOT NULL UNIQUE,
  "createdAt" TEXT NOT NULL,
  "updatedAt" TEXT NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId"    TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "account" (
  "id"                     TEXT NOT NULL PRIMARY KEY,
  "accountId"              TEXT NOT NULL,
  "providerId"             TEXT NOT NULL,
  "userId"                 TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "accessToken"            TEXT,
  "refreshToken"           TEXT,
  "idToken"                TEXT,
  "accessTokenExpiresAt"   TEXT,
  "refreshTokenExpiresAt"  TEXT,
  "scope"                  TEXT,
  "password"               TEXT,
  "createdAt"              TEXT NOT NULL,
  "updatedAt"              TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "verification" (
  "id"         TEXT NOT NULL PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value"      TEXT NOT NULL,
  "expiresAt"  TEXT NOT NULL,
  "createdAt"  TEXT NOT NULL,
  "updatedAt"  TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "oauthApplication" (
  "id"           TEXT NOT NULL PRIMARY KEY,
  "name"         TEXT NOT NULL,
  "icon"         TEXT,
  "metadata"     TEXT,
  "clientId"     TEXT NOT NULL UNIQUE,
  "clientSecret" TEXT,
  "redirectUrls" TEXT NOT NULL,
  "type"         TEXT NOT NULL,
  "disabled"     INTEGER,
  "userId"       TEXT REFERENCES "user" ("id") ON DELETE CASCADE,
  "createdAt"    TEXT NOT NULL,
  "updatedAt"    TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "oauthAccessToken" (
  "id"                     TEXT NOT NULL PRIMARY KEY,
  "accessToken"            TEXT NOT NULL UNIQUE,
  "refreshToken"           TEXT NOT NULL UNIQUE,
  "accessTokenExpiresAt"   TEXT NOT NULL,
  "refreshTokenExpiresAt"  TEXT NOT NULL,
  "clientId"               TEXT NOT NULL REFERENCES "oauthApplication" ("clientId") ON DELETE CASCADE,
  "userId"                 TEXT REFERENCES "user" ("id") ON DELETE CASCADE,
  "scopes"                 TEXT NOT NULL,
  "createdAt"              TEXT NOT NULL,
  "updatedAt"              TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "oauthConsent" (
  "id"           TEXT NOT NULL PRIMARY KEY,
  "clientId"     TEXT NOT NULL REFERENCES "oauthApplication" ("clientId") ON DELETE CASCADE,
  "userId"       TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "scopes"       TEXT NOT NULL,
  "createdAt"    TEXT NOT NULL,
  "updatedAt"    TEXT NOT NULL,
  "consentGiven" INTEGER NOT NULL
);
CREATE INDEX "session_userId_idx"           ON "session" ("userId");
CREATE INDEX "account_userId_idx"           ON "account" ("userId");
CREATE INDEX "verification_identifier_idx"  ON "verification" ("identifier");
CREATE INDEX "oauthApplication_userId_idx"  ON "oauthApplication" ("userId");
CREATE INDEX "oauthAccessToken_clientId_idx" ON "oauthAccessToken" ("clientId");
CREATE INDEX "oauthAccessToken_userId_idx"   ON "oauthAccessToken" ("userId");
CREATE INDEX "oauthConsent_clientId_idx"    ON "oauthConsent" ("clientId");
CREATE INDEX "oauthConsent_userId_idx"      ON "oauthConsent" ("userId");
CREATE TABLE memberships (
  user_id     TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  chapter_id  INTEGER NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  role        TEXT NOT NULL CHECK (role IN ('organizer', 'member')),
  status      TEXT NOT NULL CHECK (status IN ('pending', 'active')),
  created_at  INTEGER NOT NULL DEFAULT (unixepoch()),
  approved_at INTEGER,
  PRIMARY KEY (user_id, chapter_id)
);
CREATE INDEX idx_memberships_chapter ON memberships(chapter_id, status);
CREATE INDEX idx_memberships_user    ON memberships(user_id, status);
