-- Schema dump for @gdgjp/accounts
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE chapters (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('gdg', 'gdgoc')),
  created_at  INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE memberships (
  user_id     TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  chapter_id  INTEGER NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  role        TEXT NOT NULL CHECK (role IN ('organizer', 'member')),
  status      TEXT NOT NULL CHECK (status IN ('pending', 'active')),
  created_at  INTEGER NOT NULL DEFAULT (unixepoch()),
  approved_at INTEGER,
  PRIMARY KEY (user_id, chapter_id)
);
CREATE INDEX idx_memberships_chapter ON memberships(chapter_id, status);
CREATE INDEX idx_memberships_user    ON memberships(user_id, status);
CREATE TABLE IF NOT EXISTS "user" (
  id           TEXT PRIMARY KEY,
  email        TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  image        TEXT,
  is_admin     INTEGER NOT NULL DEFAULT 0,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at   INTEGER NOT NULL DEFAULT (unixepoch())
);
