import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/public/home.tsx"),
  route("links", "routes/dashboard/dashboard.tsx"),
  route("campaigns", "routes/campaigns/campaigns.tsx"),
  route("campaigns/:id", "routes/campaigns/campaigns.$id.tsx"),
  route("api/links", "routes/api/api.links.tsx"),
  route("api/images/upload", "routes/api/api.images.upload.ts"),
  route("api/cli/v1/links", "routes/api/cli/links/api.cli.v1.links.ts"),
  route("api/cli/v1/links/:id", "routes/api/cli/links/api.cli.v1.links.$id.ts"),
  route("api/cli/v1/tags", "routes/api/cli/tags/api.cli.v1.tags.ts"),
  route("api/cli/v1/tags/:id", "routes/api/cli/tags/api.cli.v1.tags.$id.ts"),
  route("api/cli/v1/folders", "routes/api/cli/folders/api.cli.v1.folders.ts"),
  route("api/cli/v1/folders/:id", "routes/api/cli/folders/api.cli.v1.folders.$id.ts"),
  route("api/cli/v1/domains", "routes/api/cli/domains/api.cli.v1.domains.ts"),
  route("api/cli/v1/domains/:id", "routes/api/cli/domains/api.cli.v1.domains.$id.ts"),
  route("api/cli/v1/domains/:id/sync", "routes/api/cli/domains/api.cli.v1.domains.$id.sync.ts"),
  route("api/cli/v1/campaigns", "routes/api/cli/campaigns/api.cli.v1.campaigns.ts"),
  route("api/cli/v1/campaigns/:id", "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.ts"),
  route(
    "api/cli/v1/campaigns/:id/restore",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.restore.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/analytics",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.analytics.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/channels",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.channels.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/channels/:channelId",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.channels.$channelId.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/channels/:channelId/restore",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.channels.$channelId.restore.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/channels/:channelId/sources",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.channels.$channelId.sources.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/channels/:channelId/sources/:sourceId",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.channels.$channelId.sources.$sourceId.ts",
  ),
  route(
    "api/cli/v1/campaigns/:id/channels/:channelId/sources/:sourceId/restore",
    "routes/api/cli/campaigns/api.cli.v1.campaigns.$id.channels.$channelId.sources.$sourceId.restore.ts",
  ),
  route("links/:id", "routes/links/links.$id.tsx"),
  route("analytics", "routes/analytics/analytics.tsx"),
  route("tags", "routes/tags/tags.tsx"),
  route("folders", "routes/folders/folders.tsx"),
  route("folders/:id", "routes/folders/folders.$id.tsx"),
  route("domains", "routes/domains/domains.tsx"),
  route("signin", "routes/auth/signin.tsx"),
  route("no-chapter", "routes/auth/no-chapter.tsx"),
  route("api/auth/*", "routes/api/api.auth.$.ts"),
  route("auth/signout", "routes/auth/auth.signout.ts"),
  route("notfound", "routes/public/notfound.tsx"),
  route(":slug", "routes/public/$slug.tsx"),
] satisfies RouteConfig;
