#!/usr/bin/env bash
# Idempotent layout generator for Stage 07. Safe to run with a prefix in tests.
# Does not create OS users. Privileged useradd/chown commands are printed by setup.sh.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPEC="${GDG_SPEC:-$here/../agent-host.json}"

if [[ ! -f "$SPEC" ]]; then
  echo "spec file not found: $SPEC" >&2
  exit 1
fi

load_spec_paths_and_slot() {
  node -e '
    const fs = require("fs");
    const specPath = process.argv[1];
    let spec;
    try {
      spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
    } catch (e) {
      console.error("Failed to parse spec at " + specPath + ": " + e.message);
      process.exit(1);
    }
    if (typeof spec.slotCount !== "number" || spec.slotCount < 1 || !Number.isInteger(spec.slotCount)) {
      console.error("spec.slotCount must be a positive integer in " + specPath);
      process.exit(1);
    }
    if (!spec.paths || typeof spec.paths !== "object") {
      console.error("spec.paths must be an object in " + specPath);
      process.exit(1);
    }
    for (const k of ["agentRoot", "workspace", "runRoot"]) {
      if (typeof spec.paths[k] !== "string" || spec.paths[k].trim().length === 0) {
        console.error("spec.paths." + k + " must be a non-empty string in " + specPath);
        process.exit(1);
      }
    }
    process.stdout.write(`SPEC_SLOT_COUNT=${spec.slotCount}\n`);
    process.stdout.write(`SPEC_AGENT_ROOT=${JSON.stringify(spec.paths.agentRoot)}\n`);
    process.stdout.write(`SPEC_WIKI_ROOT=${JSON.stringify(spec.paths.workspace)}\n`);
    process.stdout.write(`SPEC_RUN_ROOT=${JSON.stringify(spec.paths.runRoot)}\n`);
  ' "$SPEC"
}

eval "$(load_spec_paths_and_slot)"
SLOT_COUNT="${GDG_AGENT_SLOT_COUNT:-$SPEC_SLOT_COUNT}"
PREFIX="${GDG_SETUP_PREFIX:-}"
AGENT_ROOT="${GDG_SETUP_AGENT_ROOT:-${PREFIX}${SPEC_AGENT_ROOT}}"
WIKI_ROOT="${GDG_SETUP_WIKI_ROOT:-${PREFIX}${SPEC_WIKI_ROOT}}"
RUN_ROOT="${GDG_SETUP_RUN_ROOT:-${PREFIX}${SPEC_RUN_ROOT}}"
ETC_ROOT="${GDG_SETUP_ETC_ROOT:-${PREFIX}/etc}"
HOME_ROOT="${GDG_SETUP_HOME_ROOT:-${PREFIX}/home}"
HOOKS_SRC="${GDG_SETUP_HOOKS_SRC:-}"
INDEX_PROXY_SRC="${GDG_SETUP_INDEX_PROXY_SRC:-}"
if [[ -d "$here/config" ]]; then
  CONFIG_SRC="$here/config"
elif [[ -d "$here/../config" ]]; then
  CONFIG_SRC="$(cd "$here/../config" && pwd)"
else
  echo "missing layout config next to $here" >&2
  exit 1
fi

resolve_extra_mcp() {
  if [[ -f "$CONFIG_SRC/extra-mcp.json" ]]; then
    printf '%s\n' "$CONFIG_SRC/extra-mcp.json"
  elif [[ -f "$here/../config/extra-mcp.json" ]]; then
    printf '%s\n' "$(cd "$here/../config" && pwd)/extra-mcp.json"
  else
    echo "missing extra-mcp.json in $CONFIG_SRC" >&2
    exit 1
  fi
}

EXTRA_MCP="$(resolve_extra_mcp)"

merge_slot_mcp() {
  local base="$1"
  local extra="$2"
  local out="$3"
  node -e '
const fs = require("fs");
const base = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
const extra = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
if (!base.mcpServers || typeof base.mcpServers !== "object") {
  throw new Error("base mcp.json missing mcpServers");
}
if (!extra.mcpServers || typeof extra.mcpServers !== "object") {
  throw new Error("extra mcp.json missing mcpServers");
}
base.mcpServers = { ...extra.mcpServers, ...base.mcpServers };
fs.writeFileSync(process.argv[3], JSON.stringify(base, null, 2) + "\n");
' "$base" "$extra" "$out"
}

if ! [[ "$SLOT_COUNT" =~ ^[1-9][0-9]*$ ]]; then
  echo "GDG_AGENT_SLOT_COUNT must be a positive integer" >&2
  exit 1
fi
if [[ -z "$HOOKS_SRC" || ! -f "$HOOKS_SRC/acl-gate.ts" || ! -f "$HOOKS_SRC/wk.ts" || ! -f "$HOOKS_SRC/gws.ts" ]]; then
  echo "GDG_SETUP_HOOKS_SRC must point at cli/internal/wiki/hooks" >&2
  exit 1
fi
if [[ ! -f "$HOOKS_SRC/acl.ts" ]]; then
  echo "missing $HOOKS_SRC/acl.ts; run pnpm build:acl first" >&2
  exit 1
fi

writable() {
  if [[ -e "$1" ]]; then chmod u+w "$1" || true; fi
}

# Wipe bin/ from any prior install so a superseded design's wrappers (e.g. the
# retired google-workspace-mcp wrapper) never linger as dangling cruft on a
# re-provisioned host. Everything under bin/ is regenerated by this script.
rm -rf "$AGENT_ROOT/bin"

install -d -m 0755 "$AGENT_ROOT/lib" "$AGENT_ROOT/bin" "$WIKI_ROOT" "$RUN_ROOT" \
  "$ETC_ROOT/sudoers.d" "$ETC_ROOT/tmpfiles.d"

install -m 0444 "$HOOKS_SRC/package.json" "$AGENT_ROOT/package.json"
for f in acl-gate.ts wk.ts gws.ts acl-core.ts shell-allowlist.ts commit-tripwire.ts acl-insert-core.ts acl.ts exec-spawn.ts; do
  writable "$AGENT_ROOT/lib/$f"
  install -m 0444 "$HOOKS_SRC/$f" "$AGENT_ROOT/lib/$f"
done
if [[ -z "$INDEX_PROXY_SRC" || ! -f "$INDEX_PROXY_SRC" ]]; then
  echo "GDG_SETUP_INDEX_PROXY_SRC must point at agents-index/src/proxy.ts" >&2
  exit 1
fi
install -m 0444 "$INDEX_PROXY_SRC" "$AGENT_ROOT/lib/index-proxy.ts"
writable "$AGENT_ROOT/lib/cli-config.json"
sed -e "s|__AGENT_ROOT__|${SPEC_AGENT_ROOT}|g" -e "s|/opt/gdg-agent|${SPEC_AGENT_ROOT}|g" "$CONFIG_SRC/cli-config.json" > "$AGENT_ROOT/lib/cli-config.json"
chmod 0444 "$AGENT_ROOT/lib/cli-config.json"
cat > "$AGENT_ROOT/bin/index-proxy" <<EOF
#!/bin/sh
exec /usr/bin/node "$AGENT_ROOT/lib/index-proxy.ts" "\$@"
EOF
chmod 0755 "$AGENT_ROOT/bin/index-proxy"

cat > "$AGENT_ROOT/bin/wk" <<EOF
#!/bin/sh
exec /usr/bin/node "$AGENT_ROOT/lib/wk.ts" "\$@"
EOF
chmod 0755 "$AGENT_ROOT/bin/wk"

cat > "$AGENT_ROOT/bin/gws" <<EOF
#!/bin/sh
exec /usr/bin/node "$AGENT_ROOT/lib/gws.ts" "\$@"
EOF
chmod 0755 "$AGENT_ROOT/bin/gws"

mkdir -p "$ETC_ROOT/sudoers.d"
sudoers="$ETC_ROOT/sudoers.d/gdg-agent"
sudoers_tmp="$(mktemp "${ETC_ROOT}/sudoers.d/.gdg-agent.tmp.XXXXXX")"
{
  echo "# Generated by agent-host/lib/install-layout.sh. No wildcards."
  echo "Defaults:gdgagent-svc env_reset"
  for ((slot = 0; slot < SLOT_COUNT; slot++)); do
    echo "gdgagent-svc ALL=(gdgagent-run-${slot}) NOPASSWD: ${SPEC_AGENT_ROOT}/bin/spawn-slot-${slot}"
    echo "gdgagent-svc ALL=(root) NOPASSWD: /usr/bin/pkill -KILL -u gdgagent-run-${slot}"
  done
} > "$sudoers_tmp"

visudo_cmd=""
if command -v visudo >/dev/null 2>&1; then
  visudo_cmd="visudo"
elif [[ -x /usr/sbin/visudo ]]; then
  visudo_cmd="/usr/sbin/visudo"
fi

if [[ -z "$visudo_cmd" ]]; then
  echo "visudo is required to validate sudoers file before replacement" >&2
  rm -f "$sudoers_tmp"
  exit 1
fi

if ! "$visudo_cmd" -cf "$sudoers_tmp"; then
  echo "visudo validation failed for generated sudoers file" >&2
  rm -f "$sudoers_tmp"
  exit 1
fi

chmod 0440 "$sudoers_tmp"
mv -f "$sudoers_tmp" "$sudoers"

mkdir -p "$ETC_ROOT/tmpfiles.d"
tmpfiles="$ETC_ROOT/tmpfiles.d/gdg-agent.conf"
tmpfiles_tmp="$(mktemp "${ETC_ROOT}/tmpfiles.d/.gdg-agent.tmp.XXXXXX")"
{
  echo "d ${SPEC_RUN_ROOT} 0755 gdgagent-svc gdgagent-svc -"
  for ((slot = 0; slot < SLOT_COUNT; slot++)); do
    echo "d ${SPEC_RUN_ROOT}/${slot} 0750 gdgagent-svc gdgagent-run-${slot} -"
  done
} > "$tmpfiles_tmp"
chmod 0444 "$tmpfiles_tmp"
mv -f "$tmpfiles_tmp" "$tmpfiles"

for ((slot = 0; slot < SLOT_COUNT; slot++)); do
  slot_home="${HOME_ROOT}/gdgagent-run-${slot}"
  cursor_dir="${slot_home}/.cursor"
  # Sticky + group-writable so cursor-agent can mkdir projects/ and other
  # runtime dirs, but cannot unlink root-owned 0444 policy files.
  install -d -m 1775 "$cursor_dir"
  install -d -m 0755 "$cursor_dir/projects"
  # Real directory, never a symlink: Cursor refuses config paths that contain one.
  if [[ -L "$cursor_dir" || -L "$slot_home/.cursor" ]]; then
    echo "$cursor_dir must be a real directory, not a symlink" >&2
    exit 1
  fi
  writable "$cursor_dir/hooks.json"
  writable "$cursor_dir/cli-config.json"
  writable "$cursor_dir/sandbox.json"
  writable "$cursor_dir/mcp.json"
  writable "$cursor_dir/permissions.json"
  sed -e "s|__AGENT_ROOT__|${SPEC_AGENT_ROOT}|g" -e "s|/opt/gdg-agent|${SPEC_AGENT_ROOT}|g" "$CONFIG_SRC/hooks.json" > "$cursor_dir/hooks.json"
  chmod 0444 "$cursor_dir/hooks.json"
  sed -e "s|__AGENT_ROOT__|${SPEC_AGENT_ROOT}|g" -e "s|/opt/gdg-agent|${SPEC_AGENT_ROOT}|g" "$CONFIG_SRC/cli-config.json" > "$cursor_dir/cli-config.json"
  chmod 0644 "$cursor_dir/cli-config.json"
  sed -e "s|__AGENT_ROOT__|${SPEC_AGENT_ROOT}|g" -e "s|/opt/gdg-agent|${SPEC_AGENT_ROOT}|g" -e "s|__RUN_SLOT_DIR__|${SPEC_RUN_ROOT}/${slot}|g" "$CONFIG_SRC/sandbox.json.in" > "$cursor_dir/sandbox.json"
  chmod 0444 "$cursor_dir/sandbox.json"
  tmp_mcp="$(mktemp)"
  sed -e "s|__AGENT_ROOT__|${SPEC_AGENT_ROOT}|g" -e "s|/opt/gdg-agent|${SPEC_AGENT_ROOT}|g" -e "s|__INDEX_SOCKET__|${SPEC_RUN_ROOT}/${slot}/index.sock|g" "$CONFIG_SRC/mcp.json.in" > "$tmp_mcp"
  merge_slot_mcp "$tmp_mcp" "$EXTRA_MCP" "$cursor_dir/mcp.json"
  rm -f "$tmp_mcp"
  chmod 0444 "$cursor_dir/mcp.json"
  install -m 0444 "$CONFIG_SRC/permissions.json" "$cursor_dir/permissions.json"

  writable "$AGENT_ROOT/bin/spawn-slot-${slot}"
  sed -e "s|__AGENT_ROOT__|${SPEC_AGENT_ROOT}|g" -e "s|/opt/gdg-agent|${SPEC_AGENT_ROOT}|g" -e "s|__SLOT__|${slot}|g" "$CONFIG_SRC/spawn-slot.sh" > "$AGENT_ROOT/bin/spawn-slot-${slot}"
  chmod 0755 "$AGENT_ROOT/bin/spawn-slot-${slot}"

  install -d -m 0750 "$RUN_ROOT/$slot"
done

# Reconcile decommissioned slots if slotCount decreased
for spawn_script in "${AGENT_ROOT}/bin"/spawn-slot-[0-9]*; do
  [[ -f "$spawn_script" ]] || continue
  if [[ "$spawn_script" =~ spawn-slot-([0-9]+)$ ]]; then
    idx="${BASH_REMATCH[1]}"
    if (( idx >= SLOT_COUNT )); then
      rm -f "$spawn_script"
    fi
  fi
done

for run_slot in "${RUN_ROOT}"/[0-9]*; do
  [[ -d "$run_slot" ]] || continue
  idx="$(basename "$run_slot")"
  if [[ "$idx" =~ ^[0-9]+$ ]] && (( idx >= SLOT_COUNT )); then
    rm -rf "$run_slot"
  fi
done

for slot_home in "${HOME_ROOT}"/gdgagent-run-[0-9]*; do
  [[ -d "$slot_home" ]] || continue
  if [[ "$slot_home" =~ gdgagent-run-([0-9]+)$ ]]; then
    idx="${BASH_REMATCH[1]}"
    if (( idx >= SLOT_COUNT )); then
      rm -rf "${slot_home}/.cursor"
    fi
  fi
done

# Prefix/tests keep the invoking uid. Live install must match Stage 07
# (gdgagent-svc:gdgwiki 2770) before setup.sh's write checks.
if [[ -z "$PREFIX" ]] && id gdgagent-svc >/dev/null 2>&1 && getent group gdgwiki >/dev/null 2>&1; then
  chown gdgagent-svc:gdgwiki "$WIKI_ROOT"
fi
chmod 2770 "$WIKI_ROOT"
chmod 0755 "$RUN_ROOT"
echo "Installed agent layout under $AGENT_ROOT ($SLOT_COUNT slots)"
