packages:
  - "accounts"
  - "tinyurl"
  - "wiki"
  - "img"
  - "scheduler"
  - "sns"
  - "connpass"
  - "website"
  - "tinyurl-gateway"
  - "agents"
  - "go-extension"
  - "gdg-lib"
  - "accounts-oidc-client-demo"
