// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for DeleteContributorResultDeleted.
const (
	DeleteContributorResultDeletedTrue DeleteContributorResultDeleted = true
)

// Defines values for MediaDeleteResultDeleted.
const (
	MediaDeleteResultDeletedTrue MediaDeleteResultDeleted = true
)

// Defines values for PostCondition.
const (
	PostConditionPhotoRequired PostCondition = "photo_required"
	PostConditionScheduled     PostCondition = "scheduled"
)

// Defines values for PostDeleteResultDeleted.
const (
	PostDeleteResultDeletedTrue PostDeleteResultDeleted = true
)

// Defines values for PostStatus.
const (
	PostStatusFailed            PostStatus = "failed"
	PostStatusNeedsConfirmation PostStatus = "needs_confirmation"
	PostStatusPosting           PostStatus = "posting"
	PostStatusPublished         PostStatus = "published"
	PostStatusScheduled         PostStatus = "scheduled"
	PostStatusWaitingForPhoto   PostStatus = "waiting_for_photo"
)

// Defines values for RevokeXAccountResultRevoked.
const (
	RevokeXAccountResultRevokedTrue RevokeXAccountResultRevoked = true
)

// AddContributorRequest defines model for AddContributorRequest.
type AddContributorRequest struct {
	ChapterId int                 `json:"chapterId"`
	UserEmail openapi_types.Email `json:"userEmail"`
}

// AddContributorResult defines model for AddContributorResult.
type AddContributorResult struct {
	ChapterId int                 `json:"chapterId"`
	UserEmail openapi_types.Email `json:"userEmail"`
}

// Contributor defines model for Contributor.
type Contributor struct {
	CreatedAt string              `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
}

// ContributorList defines model for ContributorList.
type ContributorList struct {
	Contributors []Contributor `json:"contributors"`
	NextCursor   *string       `json:"nextCursor"`
}

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	ChapterId   int           `json:"chapterId"`
	Condition   PostCondition `json:"condition"`
	ScheduledAt string        `json:"scheduledAt"`

	// TagHandles X handles to tag; normalized and resolved through the selected X account, maximum 10.
	TagHandles *[]string `json:"tagHandles,omitempty"`
	Text       string    `json:"text"`
	XAccountId string    `json:"xAccountId"`
}

// DeleteContributorResult defines model for DeleteContributorResult.
type DeleteContributorResult struct {
	Deleted DeleteContributorResultDeleted `json:"deleted"`
}

// DeleteContributorResultDeleted defines model for DeleteContributorResult.Deleted.
type DeleteContributorResultDeleted bool

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// MediaAttachResult defines model for MediaAttachResult.
type MediaAttachResult struct {
	Media PostMedia `json:"media"`
	Post  Post      `json:"post"`
}

// MediaDeleteResult defines model for MediaDeleteResult.
type MediaDeleteResult struct {
	Deleted MediaDeleteResultDeleted `json:"deleted"`
	Id      string                   `json:"id"`
	Post    Post                     `json:"post"`
}

// MediaDeleteResultDeleted defines model for MediaDeleteResult.Deleted.
type MediaDeleteResultDeleted bool

// Post defines model for Post.
type Post struct {
	ChapterId              int           `json:"chapterId"`
	Condition              PostCondition `json:"condition"`
	CreatedAt              string        `json:"createdAt"`
	CreatedByUserId        string        `json:"createdByUserId"`
	FailureReason          *string       `json:"failureReason"`
	Id                     string        `json:"id"`
	LinkPreviewDescription *string       `json:"linkPreviewDescription"`
	LinkPreviewImageUrl    *string       `json:"linkPreviewImageUrl"`
	LinkPreviewTitle       *string       `json:"linkPreviewTitle"`
	LinkPreviewUrl         *string       `json:"linkPreviewUrl"`
	PublishedAt            *string       `json:"publishedAt"`
	PublishedXPostId       *string       `json:"publishedXPostId"`
	ScheduledAt            string        `json:"scheduledAt"`
	Status                 PostStatus    `json:"status"`
	Text                   string        `json:"text"`
	UpdatedAt              string        `json:"updatedAt"`
	XAccountId             string        `json:"xAccountId"`
}

// PostCondition defines model for PostCondition.
type PostCondition string

// PostDeleteResult defines model for PostDeleteResult.
type PostDeleteResult struct {
	Deleted PostDeleteResultDeleted `json:"deleted"`
	Id      string                  `json:"id"`
}

// PostDeleteResultDeleted defines model for PostDeleteResult.Deleted.
type PostDeleteResultDeleted bool

// PostDetailResponse defines model for PostDetailResponse.
type PostDetailResponse struct {
	Media []PostMedia `json:"media"`
	Post  Post        `json:"post"`
}

// PostList defines model for PostList.
type PostList struct {
	NextCursor *string `json:"nextCursor"`
	Posts      []Post  `json:"posts"`
}

// PostMedia defines model for PostMedia.
type PostMedia struct {
	AltText     string `json:"altText"`
	ByteSize    int    `json:"byteSize"`
	ContentType string `json:"contentType"`
	CreatedAt   string `json:"createdAt"`
	Id          string `json:"id"`
	PostId      string `json:"postId"`
	R2Key       string `json:"r2Key"`
	SortOrder   int    `json:"sortOrder"`
}

// PostResponse defines model for PostResponse.
type PostResponse struct {
	Post Post `json:"post"`
}

// PostStatus defines model for PostStatus.
type PostStatus string

// RevokeXAccountRequest defines model for RevokeXAccountRequest.
type RevokeXAccountRequest struct {
	// XUserId Must exactly match the account's current `xUserId`, to guard against an accidental revoke.
	XUserId string `json:"xUserId"`
}

// RevokeXAccountResult defines model for RevokeXAccountResult.
type RevokeXAccountResult struct {
	Id      string                      `json:"id"`
	Revoked RevokeXAccountResultRevoked `json:"revoked"`
}

// RevokeXAccountResultRevoked defines model for RevokeXAccountResult.Revoked.
type RevokeXAccountResultRevoked bool

// UpdatePostRequest Every field is optional; omitted fields are left unchanged. `linkPreview` is intentionally not accepted — preview metadata is always derived server-side from the final text.
type UpdatePostRequest struct {
	Condition   *PostCondition `json:"condition,omitempty"`
	ScheduledAt *string        `json:"scheduledAt,omitempty"`
	TagHandles  *[]string      `json:"tagHandles,omitempty"`
	Text        *string        `json:"text,omitempty"`
	XAccountId  *string        `json:"xAccountId,omitempty"`
}

// XAccountList defines model for XAccountList.
type XAccountList struct {
	Accounts []XAccountSummary `json:"accounts"`
}

// XAccountSummary defines model for XAccountSummary.
type XAccountSummary struct {
	AuthorizedByUserId string  `json:"authorizedByUserId"`
	ChapterId          int     `json:"chapterId"`
	CreatedAt          string  `json:"createdAt"`
	DisplayName        string  `json:"displayName"`
	Id                 string  `json:"id"`
	ProfileImageUrl    *string `json:"profileImageUrl"`
	RevokedAt          *string `json:"revokedAt"`
	UpdatedAt          string  `json:"updatedAt"`
	Username           string  `json:"username"`
	XUserId            string  `json:"xUserId"`
}

// ChapterIdQuery defines model for ChapterIdQuery.
type ChapterIdQuery = int

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// ResourceIdPath defines model for ResourceIdPath.
type ResourceIdPath = string

// CliBadGateway defines model for CliBadGateway.
type CliBadGateway = PostResponse

// CliBadRequest defines model for CliBadRequest.
type CliBadRequest = Error

// CliConflict defines model for CliConflict.
type CliConflict = Error

// CliForbidden defines model for CliForbidden.
type CliForbidden = Error

// CliNotFound defines model for CliNotFound.
type CliNotFound = Error

// CliPayloadTooLarge defines model for CliPayloadTooLarge.
type CliPayloadTooLarge = Error

// CliUnauthorized defines model for CliUnauthorized.
type CliUnauthorized = Error

// RemoveCliContributorParams defines parameters for RemoveCliContributor.
type RemoveCliContributorParams struct {
	ChapterId ChapterIdQuery      `form:"chapterId" json:"chapterId"`
	UserEmail openapi_types.Email `form:"userEmail" json:"userEmail"`
}

// ListCliContributorsParams defines parameters for ListCliContributors.
type ListCliContributorsParams struct {
	ChapterId ChapterIdQuery `form:"chapterId" json:"chapterId"`
	Limit     *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *Cursor        `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListCliPostsParams defines parameters for ListCliPosts.
type ListCliPostsParams struct {
	ChapterId ChapterIdQuery `form:"chapterId" json:"chapterId"`
	Status    *PostStatus    `form:"status,omitempty" json:"status,omitempty"`
	Limit     *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *Cursor        `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AttachCliPostMediaMultipartBody defines parameters for AttachCliPostMedia.
type AttachCliPostMediaMultipartBody struct {
	AltText *string `json:"altText,omitempty"`

	// File Image file
	File openapi_types.File `json:"file"`

	// SortOrder Zero-based position of this image within the post.
	SortOrder string `json:"sortOrder"`
}

// ListCliXAccountsParams defines parameters for ListCliXAccounts.
type ListCliXAccountsParams struct {
	ChapterId ChapterIdQuery `form:"chapterId" json:"chapterId"`
}

// AddCliContributorJSONRequestBody defines body for AddCliContributor for application/json ContentType.
type AddCliContributorJSONRequestBody = AddContributorRequest

// CreateCliPostJSONRequestBody defines body for CreateCliPost for application/json ContentType.
type CreateCliPostJSONRequestBody = CreatePostRequest

// UpdateCliPostJSONRequestBody defines body for UpdateCliPost for application/json ContentType.
type UpdateCliPostJSONRequestBody = UpdatePostRequest

// AttachCliPostMediaMultipartRequestBody defines body for AttachCliPostMedia for multipart/form-data ContentType.
type AttachCliPostMediaMultipartRequestBody AttachCliPostMediaMultipartBody

// RevokeCliXAccountJSONRequestBody defines body for RevokeCliXAccount for application/json ContentType.
type RevokeCliXAccountJSONRequestBody = RevokeXAccountRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RemoveCliContributor request
	RemoveCliContributor(ctx context.Context, params *RemoveCliContributorParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCliContributors request
	ListCliContributors(ctx context.Context, params *ListCliContributorsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddCliContributorWithBody request with any body
	AddCliContributorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddCliContributor(ctx context.Context, body AddCliContributorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCliMedia request
	DeleteCliMedia(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCliPosts request
	ListCliPosts(ctx context.Context, params *ListCliPostsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCliPostWithBody request with any body
	CreateCliPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCliPost(ctx context.Context, body CreateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCliPost request
	DeleteCliPost(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCliPost request
	GetCliPost(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateCliPostWithBody request with any body
	UpdateCliPostWithBody(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateCliPost(ctx context.Context, id ResourceIdPath, body UpdateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AttachCliPostMediaWithBody request with any body
	AttachCliPostMediaWithBody(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishCliPost request
	PublishCliPost(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCliXAccounts request
	ListCliXAccounts(ctx context.Context, params *ListCliXAccountsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeCliXAccountWithBody request with any body
	RevokeCliXAccountWithBody(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RevokeCliXAccount(ctx context.Context, id ResourceIdPath, body RevokeCliXAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RemoveCliContributor(ctx context.Context, params *RemoveCliContributorParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveCliContributorRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCliContributors(ctx context.Context, params *ListCliContributorsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCliContributorsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddCliContributorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddCliContributorRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddCliContributor(ctx context.Context, body AddCliContributorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddCliContributorRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCliMedia(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCliMediaRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCliPosts(ctx context.Context, params *ListCliPostsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCliPostsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCliPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCliPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCliPost(ctx context.Context, body CreateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCliPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCliPost(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCliPostRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCliPost(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCliPostRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCliPostWithBody(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCliPostRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCliPost(ctx context.Context, id ResourceIdPath, body UpdateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCliPostRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AttachCliPostMediaWithBody(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAttachCliPostMediaRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishCliPost(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishCliPostRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCliXAccounts(ctx context.Context, params *ListCliXAccountsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCliXAccountsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeCliXAccountWithBody(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeCliXAccountRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeCliXAccount(ctx context.Context, id ResourceIdPath, body RevokeCliXAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeCliXAccountRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRemoveCliContributorRequest generates requests for RemoveCliContributor
func NewRemoveCliContributorRequest(server string, params *RemoveCliContributorParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/contributors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chapterId", runtime.ParamLocationQuery, params.ChapterId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "userEmail", runtime.ParamLocationQuery, params.UserEmail); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCliContributorsRequest generates requests for ListCliContributors
func NewListCliContributorsRequest(server string, params *ListCliContributorsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/contributors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chapterId", runtime.ParamLocationQuery, params.ChapterId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddCliContributorRequest calls the generic AddCliContributor builder with application/json body
func NewAddCliContributorRequest(server string, body AddCliContributorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddCliContributorRequestWithBody(server, "application/json", bodyReader)
}

// NewAddCliContributorRequestWithBody generates requests for AddCliContributor with any type of body
func NewAddCliContributorRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/contributors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCliMediaRequest generates requests for DeleteCliMedia
func NewDeleteCliMediaRequest(server string, id ResourceIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/media/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCliPostsRequest generates requests for ListCliPosts
func NewListCliPostsRequest(server string, params *ListCliPostsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chapterId", runtime.ParamLocationQuery, params.ChapterId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCliPostRequest calls the generic CreateCliPost builder with application/json body
func NewCreateCliPostRequest(server string, body CreateCliPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCliPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCliPostRequestWithBody generates requests for CreateCliPost with any type of body
func NewCreateCliPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCliPostRequest generates requests for DeleteCliPost
func NewDeleteCliPostRequest(server string, id ResourceIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCliPostRequest generates requests for GetCliPost
func NewGetCliPostRequest(server string, id ResourceIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateCliPostRequest calls the generic UpdateCliPost builder with application/json body
func NewUpdateCliPostRequest(server string, id ResourceIdPath, body UpdateCliPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateCliPostRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateCliPostRequestWithBody generates requests for UpdateCliPost with any type of body
func NewUpdateCliPostRequestWithBody(server string, id ResourceIdPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAttachCliPostMediaRequestWithBody generates requests for AttachCliPostMedia with any type of body
func NewAttachCliPostMediaRequestWithBody(server string, id ResourceIdPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts/%s/media", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublishCliPostRequest generates requests for PublishCliPost
func NewPublishCliPostRequest(server string, id ResourceIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/posts/%s/publish", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCliXAccountsRequest generates requests for ListCliXAccounts
func NewListCliXAccountsRequest(server string, params *ListCliXAccountsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/x-accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chapterId", runtime.ParamLocationQuery, params.ChapterId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeCliXAccountRequest calls the generic RevokeCliXAccount builder with application/json body
func NewRevokeCliXAccountRequest(server string, id ResourceIdPath, body RevokeCliXAccountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRevokeCliXAccountRequestWithBody(server, id, "application/json", bodyReader)
}

// NewRevokeCliXAccountRequestWithBody generates requests for RevokeCliXAccount with any type of body
func NewRevokeCliXAccountRequestWithBody(server string, id ResourceIdPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cli/v1/x-accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RemoveCliContributorWithResponse request
	RemoveCliContributorWithResponse(ctx context.Context, params *RemoveCliContributorParams, reqEditors ...RequestEditorFn) (*RemoveCliContributorResponse, error)

	// ListCliContributorsWithResponse request
	ListCliContributorsWithResponse(ctx context.Context, params *ListCliContributorsParams, reqEditors ...RequestEditorFn) (*ListCliContributorsResponse, error)

	// AddCliContributorWithBodyWithResponse request with any body
	AddCliContributorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddCliContributorResponse, error)

	AddCliContributorWithResponse(ctx context.Context, body AddCliContributorJSONRequestBody, reqEditors ...RequestEditorFn) (*AddCliContributorResponse, error)

	// DeleteCliMediaWithResponse request
	DeleteCliMediaWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*DeleteCliMediaResponse, error)

	// ListCliPostsWithResponse request
	ListCliPostsWithResponse(ctx context.Context, params *ListCliPostsParams, reqEditors ...RequestEditorFn) (*ListCliPostsResponse, error)

	// CreateCliPostWithBodyWithResponse request with any body
	CreateCliPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCliPostResponse, error)

	CreateCliPostWithResponse(ctx context.Context, body CreateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCliPostResponse, error)

	// DeleteCliPostWithResponse request
	DeleteCliPostWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*DeleteCliPostResponse, error)

	// GetCliPostWithResponse request
	GetCliPostWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*GetCliPostResponse, error)

	// UpdateCliPostWithBodyWithResponse request with any body
	UpdateCliPostWithBodyWithResponse(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCliPostResponse, error)

	UpdateCliPostWithResponse(ctx context.Context, id ResourceIdPath, body UpdateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCliPostResponse, error)

	// AttachCliPostMediaWithBodyWithResponse request with any body
	AttachCliPostMediaWithBodyWithResponse(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AttachCliPostMediaResponse, error)

	// PublishCliPostWithResponse request
	PublishCliPostWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*PublishCliPostResponse, error)

	// ListCliXAccountsWithResponse request
	ListCliXAccountsWithResponse(ctx context.Context, params *ListCliXAccountsParams, reqEditors ...RequestEditorFn) (*ListCliXAccountsResponse, error)

	// RevokeCliXAccountWithBodyWithResponse request with any body
	RevokeCliXAccountWithBodyWithResponse(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RevokeCliXAccountResponse, error)

	RevokeCliXAccountWithResponse(ctx context.Context, id ResourceIdPath, body RevokeCliXAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*RevokeCliXAccountResponse, error)
}

type RemoveCliContributorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeleteContributorResult
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON403      *CliForbidden
}

// Status returns HTTPResponse.Status
func (r RemoveCliContributorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveCliContributorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListCliContributorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ContributorList
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON403      *CliForbidden
}

// Status returns HTTPResponse.Status
func (r ListCliContributorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCliContributorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddCliContributorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AddContributorResult
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON403      *CliForbidden
}

// Status returns HTTPResponse.Status
func (r AddCliContributorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddCliContributorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteCliMediaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MediaDeleteResult
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
	JSON409      *CliConflict
}

// Status returns HTTPResponse.Status
func (r DeleteCliMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCliMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListCliPostsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostList
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON403      *CliForbidden
}

// Status returns HTTPResponse.Status
func (r ListCliPostsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCliPostsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateCliPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PostResponse
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON403      *CliForbidden
}

// Status returns HTTPResponse.Status
func (r CreateCliPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCliPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteCliPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostDeleteResult
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
	JSON409      *CliConflict
}

// Status returns HTTPResponse.Status
func (r DeleteCliPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCliPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCliPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostDetailResponse
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
}

// Status returns HTTPResponse.Status
func (r GetCliPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCliPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateCliPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
	JSON409      *CliConflict
}

// Status returns HTTPResponse.Status
func (r UpdateCliPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateCliPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AttachCliPostMediaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *MediaAttachResult
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
	JSON409      *CliConflict
	JSON413      *CliPayloadTooLarge
}

// Status returns HTTPResponse.Status
func (r AttachCliPostMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AttachCliPostMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PublishCliPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
	JSON409      *CliConflict
	JSON502      *CliBadGateway
}

// Status returns HTTPResponse.Status
func (r PublishCliPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishCliPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListCliXAccountsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XAccountList
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON403      *CliForbidden
}

// Status returns HTTPResponse.Status
func (r ListCliXAccountsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCliXAccountsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeCliXAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RevokeXAccountResult
	JSON400      *CliBadRequest
	JSON401      *CliUnauthorized
	JSON404      *CliNotFound
}

// Status returns HTTPResponse.Status
func (r RevokeCliXAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeCliXAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RemoveCliContributorWithResponse request returning *RemoveCliContributorResponse
func (c *ClientWithResponses) RemoveCliContributorWithResponse(ctx context.Context, params *RemoveCliContributorParams, reqEditors ...RequestEditorFn) (*RemoveCliContributorResponse, error) {
	rsp, err := c.RemoveCliContributor(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveCliContributorResponse(rsp)
}

// ListCliContributorsWithResponse request returning *ListCliContributorsResponse
func (c *ClientWithResponses) ListCliContributorsWithResponse(ctx context.Context, params *ListCliContributorsParams, reqEditors ...RequestEditorFn) (*ListCliContributorsResponse, error) {
	rsp, err := c.ListCliContributors(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCliContributorsResponse(rsp)
}

// AddCliContributorWithBodyWithResponse request with arbitrary body returning *AddCliContributorResponse
func (c *ClientWithResponses) AddCliContributorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddCliContributorResponse, error) {
	rsp, err := c.AddCliContributorWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddCliContributorResponse(rsp)
}

func (c *ClientWithResponses) AddCliContributorWithResponse(ctx context.Context, body AddCliContributorJSONRequestBody, reqEditors ...RequestEditorFn) (*AddCliContributorResponse, error) {
	rsp, err := c.AddCliContributor(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddCliContributorResponse(rsp)
}

// DeleteCliMediaWithResponse request returning *DeleteCliMediaResponse
func (c *ClientWithResponses) DeleteCliMediaWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*DeleteCliMediaResponse, error) {
	rsp, err := c.DeleteCliMedia(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCliMediaResponse(rsp)
}

// ListCliPostsWithResponse request returning *ListCliPostsResponse
func (c *ClientWithResponses) ListCliPostsWithResponse(ctx context.Context, params *ListCliPostsParams, reqEditors ...RequestEditorFn) (*ListCliPostsResponse, error) {
	rsp, err := c.ListCliPosts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCliPostsResponse(rsp)
}

// CreateCliPostWithBodyWithResponse request with arbitrary body returning *CreateCliPostResponse
func (c *ClientWithResponses) CreateCliPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCliPostResponse, error) {
	rsp, err := c.CreateCliPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCliPostResponse(rsp)
}

func (c *ClientWithResponses) CreateCliPostWithResponse(ctx context.Context, body CreateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCliPostResponse, error) {
	rsp, err := c.CreateCliPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCliPostResponse(rsp)
}

// DeleteCliPostWithResponse request returning *DeleteCliPostResponse
func (c *ClientWithResponses) DeleteCliPostWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*DeleteCliPostResponse, error) {
	rsp, err := c.DeleteCliPost(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCliPostResponse(rsp)
}

// GetCliPostWithResponse request returning *GetCliPostResponse
func (c *ClientWithResponses) GetCliPostWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*GetCliPostResponse, error) {
	rsp, err := c.GetCliPost(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCliPostResponse(rsp)
}

// UpdateCliPostWithBodyWithResponse request with arbitrary body returning *UpdateCliPostResponse
func (c *ClientWithResponses) UpdateCliPostWithBodyWithResponse(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCliPostResponse, error) {
	rsp, err := c.UpdateCliPostWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCliPostResponse(rsp)
}

func (c *ClientWithResponses) UpdateCliPostWithResponse(ctx context.Context, id ResourceIdPath, body UpdateCliPostJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCliPostResponse, error) {
	rsp, err := c.UpdateCliPost(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCliPostResponse(rsp)
}

// AttachCliPostMediaWithBodyWithResponse request with arbitrary body returning *AttachCliPostMediaResponse
func (c *ClientWithResponses) AttachCliPostMediaWithBodyWithResponse(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AttachCliPostMediaResponse, error) {
	rsp, err := c.AttachCliPostMediaWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAttachCliPostMediaResponse(rsp)
}

// PublishCliPostWithResponse request returning *PublishCliPostResponse
func (c *ClientWithResponses) PublishCliPostWithResponse(ctx context.Context, id ResourceIdPath, reqEditors ...RequestEditorFn) (*PublishCliPostResponse, error) {
	rsp, err := c.PublishCliPost(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishCliPostResponse(rsp)
}

// ListCliXAccountsWithResponse request returning *ListCliXAccountsResponse
func (c *ClientWithResponses) ListCliXAccountsWithResponse(ctx context.Context, params *ListCliXAccountsParams, reqEditors ...RequestEditorFn) (*ListCliXAccountsResponse, error) {
	rsp, err := c.ListCliXAccounts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCliXAccountsResponse(rsp)
}

// RevokeCliXAccountWithBodyWithResponse request with arbitrary body returning *RevokeCliXAccountResponse
func (c *ClientWithResponses) RevokeCliXAccountWithBodyWithResponse(ctx context.Context, id ResourceIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RevokeCliXAccountResponse, error) {
	rsp, err := c.RevokeCliXAccountWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeCliXAccountResponse(rsp)
}

func (c *ClientWithResponses) RevokeCliXAccountWithResponse(ctx context.Context, id ResourceIdPath, body RevokeCliXAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*RevokeCliXAccountResponse, error) {
	rsp, err := c.RevokeCliXAccount(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeCliXAccountResponse(rsp)
}

// ParseRemoveCliContributorResponse parses an HTTP response from a RemoveCliContributorWithResponse call
func ParseRemoveCliContributorResponse(rsp *http.Response) (*RemoveCliContributorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveCliContributorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteContributorResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CliForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseListCliContributorsResponse parses an HTTP response from a ListCliContributorsWithResponse call
func ParseListCliContributorsResponse(rsp *http.Response) (*ListCliContributorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCliContributorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ContributorList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CliForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseAddCliContributorResponse parses an HTTP response from a AddCliContributorWithResponse call
func ParseAddCliContributorResponse(rsp *http.Response) (*AddCliContributorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddCliContributorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AddContributorResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CliForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteCliMediaResponse parses an HTTP response from a DeleteCliMediaWithResponse call
func ParseDeleteCliMediaResponse(rsp *http.Response) (*DeleteCliMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCliMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MediaDeleteResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CliConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseListCliPostsResponse parses an HTTP response from a ListCliPostsWithResponse call
func ParseListCliPostsResponse(rsp *http.Response) (*ListCliPostsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCliPostsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CliForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreateCliPostResponse parses an HTTP response from a CreateCliPostWithResponse call
func ParseCreateCliPostResponse(rsp *http.Response) (*CreateCliPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCliPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CliForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteCliPostResponse parses an HTTP response from a DeleteCliPostWithResponse call
func ParseDeleteCliPostResponse(rsp *http.Response) (*DeleteCliPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCliPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostDeleteResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CliConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetCliPostResponse parses an HTTP response from a GetCliPostWithResponse call
func ParseGetCliPostResponse(rsp *http.Response) (*GetCliPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCliPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateCliPostResponse parses an HTTP response from a UpdateCliPostWithResponse call
func ParseUpdateCliPostResponse(rsp *http.Response) (*UpdateCliPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateCliPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CliConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseAttachCliPostMediaResponse parses an HTTP response from a AttachCliPostMediaWithResponse call
func ParseAttachCliPostMediaResponse(rsp *http.Response) (*AttachCliPostMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AttachCliPostMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest MediaAttachResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CliConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest CliPayloadTooLarge
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParsePublishCliPostResponse parses an HTTP response from a PublishCliPostWithResponse call
func ParsePublishCliPostResponse(rsp *http.Response) (*PublishCliPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishCliPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CliConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest CliBadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseListCliXAccountsResponse parses an HTTP response from a ListCliXAccountsWithResponse call
func ParseListCliXAccountsResponse(rsp *http.Response) (*ListCliXAccountsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCliXAccountsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XAccountList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CliForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseRevokeCliXAccountResponse parses an HTTP response from a RevokeCliXAccountWithResponse call
func ParseRevokeCliXAccountResponse(rsp *http.Response) (*RevokeCliXAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeCliXAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RevokeXAccountResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
