// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for JobStatus.
const (
	Failed    JobStatus = "failed"
	Queued    JobStatus = "queued"
	Running   JobStatus = "running"
	Succeeded JobStatus = "succeeded"
)

// Defines values for JobType.
const (
	CreateEvent  JobType = "create_event"
	PublishEvent JobType = "publish_event"
	Relogin      JobType = "relogin"
	UpdateEvent  JobType = "update_event"
)

// CreateEventRequest defines model for CreateEventRequest.
type CreateEventRequest struct {
	Address     *string `json:"address,omitempty"`
	Capacity    *int    `json:"capacity,omitempty"`
	Description *string `json:"description,omitempty"`
	EndAt       *string `json:"endAt,omitempty"`
	Place       *string `json:"place,omitempty"`
	StartAt     *string `json:"startAt,omitempty"`
	Subtitle    *string `json:"subtitle,omitempty"`
	Title       string  `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Group defines model for Group.
type Group struct {
	ChapterId      *string `json:"chapterId"`
	Enabled        bool    `json:"enabled"`
	GroupId        string  `json:"groupId"`
	NumericGroupId *int    `json:"numericGroupId"`
}

// Job defines model for Job.
type Job struct {
	ArtifactKey *string                 `json:"artifactKey"`
	CreatedAt   string                  `json:"createdAt"`
	CreatedBy   string                  `json:"createdBy"`
	Error       *string                 `json:"error"`
	EventId     *string                 `json:"eventId"`
	FinishedAt  *string                 `json:"finishedAt"`
	GroupId     string                  `json:"groupId"`
	Id          string                  `json:"id"`
	Request     *map[string]interface{} `json:"request,omitempty"`
	Result      *map[string]interface{} `json:"result"`
	StartedAt   *string                 `json:"startedAt"`
	Status      JobStatus               `json:"status"`
	Type        JobType                 `json:"type"`
	UpdatedAt   string                  `json:"updatedAt"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobType defines model for Job.Type.
type JobType string

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Address     *string `json:"address,omitempty"`
	Capacity    *int    `json:"capacity,omitempty"`
	Description *string `json:"description,omitempty"`
	EndAt       *string `json:"endAt,omitempty"`
	Place       *string `json:"place,omitempty"`
	StartAt     *string `json:"startAt,omitempty"`
	Subtitle    *string `json:"subtitle,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// UpsertGroupRequest defines model for UpsertGroupRequest.
type UpsertGroupRequest struct {
	ChapterId      *string `json:"chapterId,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`
	NumericGroupId *int    `json:"numericGroupId,omitempty"`
}

// AdminUpsertGroupJSONRequestBody defines body for AdminUpsertGroup for application/json ContentType.
type AdminUpsertGroupJSONRequestBody = UpsertGroupRequest

// CreateGroupEventJSONRequestBody defines body for CreateGroupEvent for application/json ContentType.
type CreateGroupEventJSONRequestBody = CreateEventRequest

// UpdateGroupEventJSONRequestBody defines body for UpdateGroupEvent for application/json ContentType.
type UpdateGroupEventJSONRequestBody = UpdateEventRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AdminListGroups request
	AdminListGroups(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AdminUpsertGroupWithBody request with any body
	AdminUpsertGroupWithBody(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AdminUpsertGroup(ctx context.Context, groupId string, body AdminUpsertGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AdminRelogin request
	AdminRelogin(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListGroupEvents request
	ListGroupEvents(ctx context.Context, groupId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateGroupEventWithBody request with any body
	CreateGroupEventWithBody(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateGroupEvent(ctx context.Context, groupId string, body CreateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGroupEvent request
	GetGroupEvent(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateGroupEventWithBody request with any body
	UpdateGroupEventWithBody(ctx context.Context, groupId string, eventId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateGroupEvent(ctx context.Context, groupId string, eventId string, body UpdateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishGroupEvent request
	PublishGroupEvent(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob request
	GetJob(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AdminListGroups(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAdminListGroupsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AdminUpsertGroupWithBody(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAdminUpsertGroupRequestWithBody(c.Server, groupId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AdminUpsertGroup(ctx context.Context, groupId string, body AdminUpsertGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAdminUpsertGroupRequest(c.Server, groupId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AdminRelogin(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAdminReloginRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListGroupEvents(ctx context.Context, groupId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListGroupEventsRequest(c.Server, groupId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGroupEventWithBody(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGroupEventRequestWithBody(c.Server, groupId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGroupEvent(ctx context.Context, groupId string, body CreateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGroupEventRequest(c.Server, groupId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGroupEvent(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGroupEventRequest(c.Server, groupId, eventId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateGroupEventWithBody(ctx context.Context, groupId string, eventId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateGroupEventRequestWithBody(c.Server, groupId, eventId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateGroupEvent(ctx context.Context, groupId string, eventId string, body UpdateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateGroupEventRequest(c.Server, groupId, eventId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishGroupEvent(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishGroupEventRequest(c.Server, groupId, eventId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJob(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAdminListGroupsRequest generates requests for AdminListGroups
func NewAdminListGroupsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/groups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAdminUpsertGroupRequest calls the generic AdminUpsertGroup builder with application/json body
func NewAdminUpsertGroupRequest(server string, groupId string, body AdminUpsertGroupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAdminUpsertGroupRequestWithBody(server, groupId, "application/json", bodyReader)
}

// NewAdminUpsertGroupRequestWithBody generates requests for AdminUpsertGroup with any type of body
func NewAdminUpsertGroupRequestWithBody(server string, groupId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAdminReloginRequest generates requests for AdminRelogin
func NewAdminReloginRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/session/relogin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListGroupEventsRequest generates requests for ListGroupEvents
func NewListGroupEventsRequest(server string, groupId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/groups/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateGroupEventRequest calls the generic CreateGroupEvent builder with application/json body
func NewCreateGroupEventRequest(server string, groupId string, body CreateGroupEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateGroupEventRequestWithBody(server, groupId, "application/json", bodyReader)
}

// NewCreateGroupEventRequestWithBody generates requests for CreateGroupEvent with any type of body
func NewCreateGroupEventRequestWithBody(server string, groupId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/groups/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetGroupEventRequest generates requests for GetGroupEvent
func NewGetGroupEventRequest(server string, groupId string, eventId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/groups/%s/events/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateGroupEventRequest calls the generic UpdateGroupEvent builder with application/json body
func NewUpdateGroupEventRequest(server string, groupId string, eventId string, body UpdateGroupEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateGroupEventRequestWithBody(server, groupId, eventId, "application/json", bodyReader)
}

// NewUpdateGroupEventRequestWithBody generates requests for UpdateGroupEvent with any type of body
func NewUpdateGroupEventRequestWithBody(server string, groupId string, eventId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/groups/%s/events/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublishGroupEventRequest generates requests for PublishGroupEvent
func NewPublishGroupEventRequest(server string, groupId string, eventId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/groups/%s/events/%s/publish", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobRequest generates requests for GetJob
func NewGetJobRequest(server string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AdminListGroupsWithResponse request
	AdminListGroupsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AdminListGroupsResponse, error)

	// AdminUpsertGroupWithBodyWithResponse request with any body
	AdminUpsertGroupWithBodyWithResponse(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AdminUpsertGroupResponse, error)

	AdminUpsertGroupWithResponse(ctx context.Context, groupId string, body AdminUpsertGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*AdminUpsertGroupResponse, error)

	// AdminReloginWithResponse request
	AdminReloginWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AdminReloginResponse, error)

	// ListGroupEventsWithResponse request
	ListGroupEventsWithResponse(ctx context.Context, groupId string, reqEditors ...RequestEditorFn) (*ListGroupEventsResponse, error)

	// CreateGroupEventWithBodyWithResponse request with any body
	CreateGroupEventWithBodyWithResponse(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGroupEventResponse, error)

	CreateGroupEventWithResponse(ctx context.Context, groupId string, body CreateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateGroupEventResponse, error)

	// GetGroupEventWithResponse request
	GetGroupEventWithResponse(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*GetGroupEventResponse, error)

	// UpdateGroupEventWithBodyWithResponse request with any body
	UpdateGroupEventWithBodyWithResponse(ctx context.Context, groupId string, eventId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateGroupEventResponse, error)

	UpdateGroupEventWithResponse(ctx context.Context, groupId string, eventId string, body UpdateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateGroupEventResponse, error)

	// PublishGroupEventWithResponse request
	PublishGroupEventWithResponse(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*PublishGroupEventResponse, error)

	// GetJobWithResponse request
	GetJobWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*GetJobResponse, error)
}

type AdminListGroupsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Groups *[]Group `json:"groups,omitempty"`
	}
	JSON401 *Error
	JSON403 *Error
}

// Status returns HTTPResponse.Status
func (r AdminListGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AdminListGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AdminUpsertGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Group
	JSON401      *Error
	JSON403      *Error
}

// Status returns HTTPResponse.Status
func (r AdminUpsertGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AdminUpsertGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AdminReloginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Job
	JSON401      *Error
	JSON403      *Error
}

// Status returns HTTPResponse.Status
func (r AdminReloginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AdminReloginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListGroupEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON401      *Error
	JSON403      *Error
}

// Status returns HTTPResponse.Status
func (r ListGroupEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListGroupEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateGroupEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Job
	JSON400      *Error
	JSON401      *Error
	JSON403      *Error
}

// Status returns HTTPResponse.Status
func (r CreateGroupEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateGroupEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGroupEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetGroupEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGroupEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateGroupEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Job
	JSON401      *Error
	JSON403      *Error
}

// Status returns HTTPResponse.Status
func (r UpdateGroupEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateGroupEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PublishGroupEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Job
	JSON401      *Error
	JSON403      *Error
}

// Status returns HTTPResponse.Status
func (r PublishGroupEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishGroupEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Job
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AdminListGroupsWithResponse request returning *AdminListGroupsResponse
func (c *ClientWithResponses) AdminListGroupsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AdminListGroupsResponse, error) {
	rsp, err := c.AdminListGroups(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAdminListGroupsResponse(rsp)
}

// AdminUpsertGroupWithBodyWithResponse request with arbitrary body returning *AdminUpsertGroupResponse
func (c *ClientWithResponses) AdminUpsertGroupWithBodyWithResponse(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AdminUpsertGroupResponse, error) {
	rsp, err := c.AdminUpsertGroupWithBody(ctx, groupId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAdminUpsertGroupResponse(rsp)
}

func (c *ClientWithResponses) AdminUpsertGroupWithResponse(ctx context.Context, groupId string, body AdminUpsertGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*AdminUpsertGroupResponse, error) {
	rsp, err := c.AdminUpsertGroup(ctx, groupId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAdminUpsertGroupResponse(rsp)
}

// AdminReloginWithResponse request returning *AdminReloginResponse
func (c *ClientWithResponses) AdminReloginWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AdminReloginResponse, error) {
	rsp, err := c.AdminRelogin(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAdminReloginResponse(rsp)
}

// ListGroupEventsWithResponse request returning *ListGroupEventsResponse
func (c *ClientWithResponses) ListGroupEventsWithResponse(ctx context.Context, groupId string, reqEditors ...RequestEditorFn) (*ListGroupEventsResponse, error) {
	rsp, err := c.ListGroupEvents(ctx, groupId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListGroupEventsResponse(rsp)
}

// CreateGroupEventWithBodyWithResponse request with arbitrary body returning *CreateGroupEventResponse
func (c *ClientWithResponses) CreateGroupEventWithBodyWithResponse(ctx context.Context, groupId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGroupEventResponse, error) {
	rsp, err := c.CreateGroupEventWithBody(ctx, groupId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGroupEventResponse(rsp)
}

func (c *ClientWithResponses) CreateGroupEventWithResponse(ctx context.Context, groupId string, body CreateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateGroupEventResponse, error) {
	rsp, err := c.CreateGroupEvent(ctx, groupId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGroupEventResponse(rsp)
}

// GetGroupEventWithResponse request returning *GetGroupEventResponse
func (c *ClientWithResponses) GetGroupEventWithResponse(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*GetGroupEventResponse, error) {
	rsp, err := c.GetGroupEvent(ctx, groupId, eventId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGroupEventResponse(rsp)
}

// UpdateGroupEventWithBodyWithResponse request with arbitrary body returning *UpdateGroupEventResponse
func (c *ClientWithResponses) UpdateGroupEventWithBodyWithResponse(ctx context.Context, groupId string, eventId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateGroupEventResponse, error) {
	rsp, err := c.UpdateGroupEventWithBody(ctx, groupId, eventId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateGroupEventResponse(rsp)
}

func (c *ClientWithResponses) UpdateGroupEventWithResponse(ctx context.Context, groupId string, eventId string, body UpdateGroupEventJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateGroupEventResponse, error) {
	rsp, err := c.UpdateGroupEvent(ctx, groupId, eventId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateGroupEventResponse(rsp)
}

// PublishGroupEventWithResponse request returning *PublishGroupEventResponse
func (c *ClientWithResponses) PublishGroupEventWithResponse(ctx context.Context, groupId string, eventId string, reqEditors ...RequestEditorFn) (*PublishGroupEventResponse, error) {
	rsp, err := c.PublishGroupEvent(ctx, groupId, eventId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishGroupEventResponse(rsp)
}

// GetJobWithResponse request returning *GetJobResponse
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// ParseAdminListGroupsResponse parses an HTTP response from a AdminListGroupsWithResponse call
func ParseAdminListGroupsResponse(rsp *http.Response) (*AdminListGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AdminListGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Groups *[]Group `json:"groups,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseAdminUpsertGroupResponse parses an HTTP response from a AdminUpsertGroupWithResponse call
func ParseAdminUpsertGroupResponse(rsp *http.Response) (*AdminUpsertGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AdminUpsertGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Group
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseAdminReloginResponse parses an HTTP response from a AdminReloginWithResponse call
func ParseAdminReloginResponse(rsp *http.Response) (*AdminReloginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AdminReloginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseListGroupEventsResponse parses an HTTP response from a ListGroupEventsWithResponse call
func ParseListGroupEventsResponse(rsp *http.Response) (*ListGroupEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListGroupEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreateGroupEventResponse parses an HTTP response from a CreateGroupEventWithResponse call
func ParseCreateGroupEventResponse(rsp *http.Response) (*CreateGroupEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateGroupEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetGroupEventResponse parses an HTTP response from a GetGroupEventWithResponse call
func ParseGetGroupEventResponse(rsp *http.Response) (*GetGroupEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGroupEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateGroupEventResponse parses an HTTP response from a UpdateGroupEventWithResponse call
func ParseUpdateGroupEventResponse(rsp *http.Response) (*UpdateGroupEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateGroupEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePublishGroupEventResponse parses an HTTP response from a PublishGroupEventWithResponse call
func ParsePublishGroupEventResponse(rsp *http.Response) (*PublishGroupEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishGroupEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
