name = "gdgjp-scheduler"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[alias]
"virtual:react-router/server-build" = "./build/server/index.js"

[vars]
APP_URL = "https://scheduler.gdgs.jp"
ACCOUNTS_URL = "https://accounts.gdgs.jp"
IDP_URL = "https://accounts.gdgs.jp"
IDP_CLIENT_ID = "scheduler"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gdgjp-scheduler-db"
database_id = "67a5f81e-ec0c-4027-90d5-a7eb7e3ad0ae"
migrations_dir = "./migrations"

# [[routes]]
# pattern = "scheduler.gdgs.jp/*"
# zone_name = "gdgs.jp"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
