#!/usr/bin/env bash
# Idempotent layout generator for Stage 07. Safe to run with a prefix in tests.
# Does not create OS users. Privileged useradd/chown commands are printed by setup.sh.
set -euo pipefail

SLOT_COUNT="${GDG_AGENT_SLOT_COUNT:-4}"
PREFIX="${GDG_SETUP_PREFIX:-}"
AGENT_ROOT="${GDG_SETUP_AGENT_ROOT:-${PREFIX}/opt/gdg-agent}"
WIKI_ROOT="${GDG_SETUP_WIKI_ROOT:-${PREFIX}/srv/gdg-agent/wiki}"
RUN_ROOT="${GDG_SETUP_RUN_ROOT:-${PREFIX}/run/gdg-agent}"
ETC_ROOT="${GDG_SETUP_ETC_ROOT:-${PREFIX}/etc}"
HOME_ROOT="${GDG_SETUP_HOME_ROOT:-${PREFIX}/home}"
HOOKS_SRC="${GDG_SETUP_HOOKS_SRC:-}"
INDEX_PROXY_SRC="${GDG_SETUP_INDEX_PROXY_SRC:-}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -d "$here/config" ]]; then
  CONFIG_SRC="$here/config"
elif [[ -d "$here/../config" ]]; then
  CONFIG_SRC="$(cd "$here/../config" && pwd)"
else
  echo "missing layout config next to $here" >&2
  exit 1
fi

resolve_extra_mcp() {
  if [[ -f "$here/../.cursor/mcp.json" ]]; then
    printf '%s\n' "$(cd "$here/.." && pwd)/.cursor/mcp.json"
  elif [[ -f "$here/../../agents-local/.cursor/mcp.json" ]]; then
    printf '%s\n' "$(cd "$here/../../agents-local" && pwd)/.cursor/mcp.json"
  else
    echo "missing agents-local/.cursor/mcp.json (looked next to $here)" >&2
    exit 1
  fi
}

EXTRA_MCP="$(resolve_extra_mcp)"

merge_slot_mcp() {
  local base="$1"
  local extra="$2"
  local out="$3"
  node -e '
const fs = require("fs");
const base = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
const extra = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
if (!base.mcpServers || typeof base.mcpServers !== "object") {
  throw new Error("base mcp.json missing mcpServers");
}
if (!extra.mcpServers || typeof extra.mcpServers !== "object") {
  throw new Error("extra mcp.json missing mcpServers");
}
base.mcpServers = { ...extra.mcpServers, ...base.mcpServers };
fs.writeFileSync(process.argv[3], JSON.stringify(base, null, 2) + "\n");
' "$base" "$extra" "$out"
}

if ! [[ "$SLOT_COUNT" =~ ^[1-9][0-9]*$ ]]; then
  echo "GDG_AGENT_SLOT_COUNT must be a positive integer" >&2
  exit 1
fi
if [[ -z "$HOOKS_SRC" || ! -f "$HOOKS_SRC/acl-gate.ts" || ! -f "$HOOKS_SRC/wk.ts" ]]; then
  echo "GDG_SETUP_HOOKS_SRC must point at cli/internal/wiki/hooks" >&2
  exit 1
fi
if [[ ! -f "$HOOKS_SRC/acl.ts" ]]; then
  echo "missing $HOOKS_SRC/acl.ts; run pnpm build:acl first" >&2
  exit 1
fi

writable() {
  if [[ -e "$1" ]]; then chmod u+w "$1" || true; fi
}

install -d -m 0755 "$AGENT_ROOT/lib" "$AGENT_ROOT/bin" "$WIKI_ROOT" "$RUN_ROOT" \
  "$ETC_ROOT/sudoers.d" "$ETC_ROOT/tmpfiles.d"

install -m 0444 "$HOOKS_SRC/package.json" "$AGENT_ROOT/package.json"
for f in acl-gate.ts wk.ts acl-core.ts shell-allowlist.ts commit-tripwire.ts acl-insert-core.ts acl.ts exec-spawn.ts; do
  writable "$AGENT_ROOT/lib/$f"
  install -m 0444 "$HOOKS_SRC/$f" "$AGENT_ROOT/lib/$f"
done
if [[ -z "$INDEX_PROXY_SRC" || ! -f "$INDEX_PROXY_SRC" ]]; then
  echo "GDG_SETUP_INDEX_PROXY_SRC must point at agents-index/src/proxy.ts" >&2
  exit 1
fi
install -m 0444 "$CONFIG_SRC/cli-config.json" "$AGENT_ROOT/lib/cli-config.json"
install -m 0444 "$INDEX_PROXY_SRC" "$AGENT_ROOT/lib/index-proxy.ts"
cat > "$AGENT_ROOT/bin/index-proxy" <<EOF
#!/bin/sh
exec /usr/bin/node "$AGENT_ROOT/lib/index-proxy.ts" "\$@"
EOF
chmod 0755 "$AGENT_ROOT/bin/index-proxy"

cat > "$AGENT_ROOT/bin/wk" <<EOF
#!/bin/sh
exec /usr/bin/node "$AGENT_ROOT/lib/wk.ts" "\$@"
EOF
chmod 0755 "$AGENT_ROOT/bin/wk"

sudoers="$ETC_ROOT/sudoers.d/gdg-agent"
if [[ -f "$sudoers" ]]; then
  chmod u+w "$sudoers" || true
fi
{
  echo "# Generated by agents-local/lib/install-layout.sh. No wildcards."
  echo "Defaults:gdgagent-svc env_reset"
  for ((slot = 0; slot < SLOT_COUNT; slot++)); do
    echo "gdgagent-svc ALL=(gdgagent-run-${slot}) NOPASSWD: /opt/gdg-agent/bin/spawn-slot-${slot}"
    echo "gdgagent-svc ALL=(root) NOPASSWD: /usr/bin/pkill -KILL -u gdgagent-run-${slot}"
  done
} > "$sudoers"
chmod 0440 "$sudoers"

tmpfiles="$ETC_ROOT/tmpfiles.d/gdg-agent.conf"
if [[ -f "$tmpfiles" ]]; then
  chmod u+w "$tmpfiles" || true
fi
{
  echo "d /run/gdg-agent 0755 gdgagent-svc gdgagent-svc -"
  for ((slot = 0; slot < SLOT_COUNT; slot++)); do
    echo "d /run/gdg-agent/${slot} 0750 gdgagent-svc gdgagent-run-${slot} -"
  done
} > "$tmpfiles"
chmod 0444 "$tmpfiles"

for ((slot = 0; slot < SLOT_COUNT; slot++)); do
  slot_home="${HOME_ROOT}/gdgagent-run-${slot}"
  cursor_dir="${slot_home}/.cursor"
  # Sticky + group-writable so cursor-agent can mkdir projects/ and other
  # runtime dirs, but cannot unlink root-owned 0444 policy files.
  install -d -m 1775 "$cursor_dir"
  install -d -m 0755 "$cursor_dir/projects"
  # Real directory, never a symlink: Cursor refuses config paths that contain one.
  if [[ -L "$cursor_dir" || -L "$slot_home/.cursor" ]]; then
    echo "$cursor_dir must be a real directory, not a symlink" >&2
    exit 1
  fi
  writable "$cursor_dir/hooks.json"
  writable "$cursor_dir/cli-config.json"
  writable "$cursor_dir/sandbox.json"
  writable "$cursor_dir/mcp.json"
  install -m 0444 "$CONFIG_SRC/hooks.json" "$cursor_dir/hooks.json"
  install -m 0644 "$CONFIG_SRC/cli-config.json" "$cursor_dir/cli-config.json"
  sed "s|__RUN_SLOT_DIR__|/run/gdg-agent/${slot}|g" "$CONFIG_SRC/sandbox.json.in" > "$cursor_dir/sandbox.json"
  chmod 0444 "$cursor_dir/sandbox.json"
  tmp_mcp="$(mktemp)"
  sed "s|__INDEX_SOCKET__|/run/gdg-agent/${slot}/index.sock|g" "$CONFIG_SRC/mcp.json.in" > "$tmp_mcp"
  merge_slot_mcp "$tmp_mcp" "$EXTRA_MCP" "$cursor_dir/mcp.json"
  rm -f "$tmp_mcp"
  chmod 0444 "$cursor_dir/mcp.json"

  writable "$AGENT_ROOT/bin/spawn-slot-${slot}"
  sed "s|__SLOT__|${slot}|g" "$CONFIG_SRC/spawn-slot.sh" > "$AGENT_ROOT/bin/spawn-slot-${slot}"
  chmod 0755 "$AGENT_ROOT/bin/spawn-slot-${slot}"

  install -d -m 0750 "$RUN_ROOT/$slot"
done

# Prefix/tests keep the invoking uid. Live install must match Stage 07
# (gdgagent-svc:gdgwiki 2770) before setup.sh's write checks.
if [[ -z "$PREFIX" ]] && id gdgagent-svc >/dev/null 2>&1 && getent group gdgwiki >/dev/null 2>&1; then
  chown gdgagent-svc:gdgwiki "$WIKI_ROOT"
fi
chmod 2770 "$WIKI_ROOT"
chmod 0755 "$RUN_ROOT"
echo "Installed agent layout under $AGENT_ROOT ($SLOT_COUNT slots)"
