/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a short URL */
        get: operations["resolveShortUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a short URL through the /r alias */
        get: operations["resolveShortUrlAlias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/gateway/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the active custom-domain gateway configuration */
        get: operations["getGatewayConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/gateway/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a custom-domain short URL through the gateway */
        get: operations["resolveGatewayShortUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List domains visible to the caller */
        get: operations["listCliDomains"];
        put?: never;
        /** Register a custom domain and provision it asynchronously */
        post: operations["createCliDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a domain by id */
        get: operations["getCliDomain"];
        put?: never;
        post?: never;
        /** Soft-delete a custom domain */
        delete: operations["deleteCliDomain"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/domains/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry provisioning for a non-active domain */
        post: operations["syncCliDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an async job's status */
        get: operations["getCliJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GatewayConfig: {
            /** Format: hostname */
            hostname: string;
            /** @enum {string} */
            mode: "short-only" | "origin-first";
            /** Format: uri */
            upstreamOrigin: string | null;
        };
        Error: {
            error: string;
        };
        DnsRecord: {
            /** @enum {string} */
            type: "A" | "AAAA" | "CNAME" | "TXT" | "CAA";
            name: string;
            value: string;
            reason?: string;
            /** @enum {string} */
            purpose?: "ownership" | "routing";
            /** @enum {string} */
            status?: "pending" | "verified";
            /** @enum {string} */
            alternativeGroup?: "apex-routing";
        };
        Domain: {
            id: number;
            hostname: string;
            /** @enum {string} */
            kind: "system" | "custom";
            /** @enum {string} */
            mode: "short-only" | "origin-first";
            upstreamOrigin: string | null;
            ownerChapterId: number | null;
            /** @enum {string} */
            status: "pending" | "verifying" | "active" | "error" | "deleted";
            providerDomainId: string | null;
            verificationRecords: components["schemas"]["DnsRecord"][];
            providerError: string | null;
            createdByUserId: string | null;
            /** @description Unix seconds. */
            createdAt: number;
            /** @description Unix seconds. */
            updatedAt: number;
            /** @description Unix seconds. */
            checkedAt: number | null;
            /** @description Unix seconds. */
            deletedAt: number | null;
        };
        DomainList: {
            domains: components["schemas"]["Domain"][];
            nextCursor: string | null;
        };
        DomainResponse: {
            domain: components["schemas"]["Domain"];
        };
        DomainDeleteResult: {
            id: number;
            /** @enum {boolean} */
            deleted: true;
        };
        Job: {
            id: string;
            /** @enum {string} */
            type: "provision_domain";
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            domainId: number;
            request: {
                [key: string]: unknown;
            };
            /** @description The persisted success or error-state Domain snapshot, once finished. */
            result: {
                [key: string]: unknown;
            } | null;
            error: string | null;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
        };
        JobResponse: {
            job: components["schemas"]["Job"];
        };
    };
    responses: {
        /** @description The gateway signature is missing, invalid, or expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description The requested short URL or domain does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description The request is missing required fields or is malformed. */
        CliBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The bearer token is missing, invalid, or lacks the CLI scope. */
        CliUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller cannot act on this domain or chapter. */
        CliForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Domain or job not found. */
        CliNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the resource's current state. */
        CliConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The job could not be queued; retry later. */
        CliServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Slug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolveShortUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML preview returned to crawler user agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Redirect to the destination URL. */
            302: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    resolveShortUrlAlias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML preview returned to crawler user agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Redirect to the destination URL. */
            302: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getGatewayConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    resolveGatewayShortUrl: {
        parameters: {
            query: {
                slug?: string;
                hostname: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No slug was provided or no matching link exists. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Redirect to the destination URL. */
            302: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCliDomains: {
        parameters: {
            query?: {
                chapterId?: number;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's visible domains. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainList"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    createCliDomain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    hostname: string;
                    chapterId: number;
                };
            };
        };
        responses: {
            /** @description The domain was created and a provisioning job was queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            503: components["responses"]["CliServiceUnavailable"];
        };
    };
    getCliDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The domain. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
        };
    };
    deleteCliDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The domain was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainDeleteResult"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
        };
    };
    syncCliDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A resynchronization job was queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
            503: components["responses"]["CliServiceUnavailable"];
        };
    };
    getCliJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
        };
    };
}
