-- Schema dump for @gdgjp/tinyurl
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE _migrations_seed (
  id INTEGER PRIMARY KEY
);
CREATE TABLE tags (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  name             TEXT NOT NULL,
  color            TEXT,
  owner_user_id    TEXT,
  owner_chapter_id INTEGER,
  created_at       INTEGER NOT NULL DEFAULT (unixepoch()),
  CHECK (
    (owner_user_id IS NOT NULL AND owner_chapter_id IS NULL) OR
    (owner_user_id IS NULL AND owner_chapter_id IS NOT NULL)
  )
);
CREATE UNIQUE INDEX idx_tags_user_name
  ON tags(owner_user_id, name) WHERE owner_user_id IS NOT NULL;
CREATE UNIQUE INDEX idx_tags_chapter_name
  ON tags(owner_chapter_id, name) WHERE owner_chapter_id IS NOT NULL;
CREATE TABLE links (
  id              TEXT PRIMARY KEY,
  slug            TEXT NOT NULL UNIQUE,
  destination_url TEXT NOT NULL,
  title           TEXT,
  description     TEXT,
  og_image_url    TEXT,
  owner_user_id   TEXT NOT NULL,
  owner_chapter_id INTEGER,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at      INTEGER
, visibility TEXT NOT NULL DEFAULT 'private'
  CHECK (visibility IN ('private', 'public')), campaign_channel_id INTEGER
  REFERENCES campaign_channels(id) ON DELETE SET NULL);
CREATE TABLE link_tags (
  link_id TEXT NOT NULL,
  tag_id  INTEGER NOT NULL,
  PRIMARY KEY (link_id, tag_id),
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id)  REFERENCES tags(id)  ON DELETE CASCADE
);
CREATE TABLE comments (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  link_id         TEXT NOT NULL,
  author_user_id  TEXT NOT NULL,
  body            TEXT NOT NULL,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
);
CREATE TABLE link_permissions (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  link_id        TEXT NOT NULL,
  principal_type TEXT NOT NULL CHECK (principal_type IN ('user', 'chapter')),
  principal_id   TEXT NOT NULL,
  role           TEXT NOT NULL CHECK (role IN ('editor', 'viewer')),
  created_at     INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE(link_id, principal_type, principal_id),
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
);
CREATE INDEX idx_links_owner            ON links(owner_user_id, deleted_at);
CREATE INDEX idx_links_chapter          ON links(owner_chapter_id, deleted_at);
CREATE INDEX idx_link_tags_tag          ON link_tags(tag_id);
CREATE INDEX idx_comments_link          ON comments(link_id, created_at);
CREATE INDEX idx_link_permissions_link  ON link_permissions(link_id);
CREATE INDEX idx_link_permissions_user
  ON link_permissions(principal_type, principal_id) WHERE principal_type = 'user';
CREATE INDEX idx_link_permissions_chapter
  ON link_permissions(principal_type, principal_id) WHERE principal_type = 'chapter';
CREATE TABLE IF NOT EXISTS "user" (
  "id"            TEXT NOT NULL PRIMARY KEY,
  "name"          TEXT NOT NULL,
  "email"         TEXT NOT NULL UNIQUE,
  "image"         TEXT,
  "is_admin" INTEGER NOT NULL DEFAULT 0, "created_at" INTEGER NOT NULL DEFAULT 0, "updated_at" INTEGER NOT NULL DEFAULT 0);
CREATE INDEX idx_links_visibility ON links(visibility, deleted_at);
CREATE TABLE campaigns (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  name               TEXT NOT NULL,
  code               TEXT NOT NULL COLLATE NOCASE,
  default_destination_url TEXT,
  owner_chapter_id   INTEGER NOT NULL,
  created_by_user_id TEXT NOT NULL,
  created_at         INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at         INTEGER NOT NULL DEFAULT (unixepoch()),
  archived_at        INTEGER,
  UNIQUE(owner_chapter_id, code)
);
CREATE INDEX idx_campaigns_chapter
  ON campaigns(owner_chapter_id, archived_at, created_at DESC);
CREATE TABLE campaign_channels (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  campaign_id INTEGER NOT NULL,
  name        TEXT NOT NULL,
  code        TEXT NOT NULL COLLATE NOCASE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  archived_at INTEGER,
  UNIQUE(campaign_id, code),
  FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);
CREATE INDEX idx_campaign_channels_campaign
  ON campaign_channels(campaign_id, archived_at, sort_order, id);
CREATE TABLE campaign_channel_sources (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id  INTEGER NOT NULL,
  name        TEXT NOT NULL,
  code        TEXT NOT NULL COLLATE NOCASE,
  archived_at INTEGER,
  UNIQUE(channel_id, code),
  FOREIGN KEY (channel_id) REFERENCES campaign_channels(id) ON DELETE CASCADE
);
CREATE INDEX idx_campaign_channel_sources_channel
  ON campaign_channel_sources(channel_id, archived_at, name, id);
CREATE INDEX idx_links_campaign_channel
  ON links(campaign_channel_id, deleted_at, created_at DESC);
