-- Schema dump for @gdgjp/tinyurl
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE _migrations_seed (
  id INTEGER PRIMARY KEY
);
CREATE TABLE tags (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  name             TEXT NOT NULL,
  color            TEXT,
  owner_user_id    TEXT,
  owner_chapter_id INTEGER,
  created_at       INTEGER NOT NULL DEFAULT (unixepoch()),
  CHECK (
    (owner_user_id IS NOT NULL AND owner_chapter_id IS NULL) OR
    (owner_user_id IS NULL AND owner_chapter_id IS NOT NULL)
  )
);
CREATE UNIQUE INDEX idx_tags_user_name
  ON tags(owner_user_id, name) WHERE owner_user_id IS NOT NULL;
CREATE UNIQUE INDEX idx_tags_chapter_name
  ON tags(owner_chapter_id, name) WHERE owner_chapter_id IS NOT NULL;
CREATE TABLE links (
  id              TEXT PRIMARY KEY,
  slug            TEXT NOT NULL UNIQUE,
  destination_url TEXT NOT NULL,
  title           TEXT,
  description     TEXT,
  og_image_url    TEXT,
  owner_user_id   TEXT NOT NULL,
  owner_chapter_id INTEGER,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at      INTEGER
, visibility TEXT NOT NULL DEFAULT 'private'
  CHECK (visibility IN ('private', 'public')));
CREATE TABLE link_tags (
  link_id TEXT NOT NULL,
  tag_id  INTEGER NOT NULL,
  PRIMARY KEY (link_id, tag_id),
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id)  REFERENCES tags(id)  ON DELETE CASCADE
);
CREATE TABLE comments (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  link_id         TEXT NOT NULL,
  author_user_id  TEXT NOT NULL,
  body            TEXT NOT NULL,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
);
CREATE TABLE link_permissions (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  link_id        TEXT NOT NULL,
  principal_type TEXT NOT NULL CHECK (principal_type IN ('user', 'chapter')),
  principal_id   TEXT NOT NULL,
  role           TEXT NOT NULL CHECK (role IN ('editor', 'viewer')),
  created_at     INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE(link_id, principal_type, principal_id),
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
);
CREATE INDEX idx_links_owner            ON links(owner_user_id, deleted_at);
CREATE INDEX idx_links_chapter          ON links(owner_chapter_id, deleted_at);
CREATE INDEX idx_link_tags_tag          ON link_tags(tag_id);
CREATE INDEX idx_comments_link          ON comments(link_id, created_at);
CREATE INDEX idx_link_permissions_link  ON link_permissions(link_id);
CREATE INDEX idx_link_permissions_user
  ON link_permissions(principal_type, principal_id) WHERE principal_type = 'user';
CREATE INDEX idx_link_permissions_chapter
  ON link_permissions(principal_type, principal_id) WHERE principal_type = 'chapter';
CREATE TABLE IF NOT EXISTS "user" (
  "id"            TEXT NOT NULL PRIMARY KEY,
  "name"          TEXT NOT NULL,
  "email"         TEXT NOT NULL UNIQUE,
  "emailVerified" INTEGER NOT NULL,
  "image"         TEXT,
  "createdAt"     TEXT NOT NULL,
  "updatedAt"     TEXT NOT NULL,
  "isAdmin"       INTEGER
);
CREATE TABLE IF NOT EXISTS "session" (
  "id"        TEXT NOT NULL PRIMARY KEY,
  "expiresAt" TEXT NOT NULL,
  "token"     TEXT NOT NULL UNIQUE,
  "createdAt" TEXT NOT NULL,
  "updatedAt" TEXT NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId"    TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "account" (
  "id"                     TEXT NOT NULL PRIMARY KEY,
  "accountId"              TEXT NOT NULL,
  "providerId"             TEXT NOT NULL,
  "userId"                 TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "accessToken"            TEXT,
  "refreshToken"           TEXT,
  "idToken"                TEXT,
  "accessTokenExpiresAt"   TEXT,
  "refreshTokenExpiresAt"  TEXT,
  "scope"                  TEXT,
  "password"               TEXT,
  "createdAt"              TEXT NOT NULL,
  "updatedAt"              TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "verification" (
  "id"         TEXT NOT NULL PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value"      TEXT NOT NULL,
  "expiresAt"  TEXT NOT NULL,
  "createdAt"  TEXT NOT NULL,
  "updatedAt"  TEXT NOT NULL
);
CREATE INDEX "session_userId_idx"          ON "session" ("userId");
CREATE INDEX "account_userId_idx"          ON "account" ("userId");
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");
CREATE INDEX idx_links_visibility ON links(visibility, deleted_at);
