name = "gdgjp-tinyurl"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[alias]
"virtual:react-router/server-build" = "./build/server/index.js"

[vars]
APP_URL = "https://url.gdgs.jp"
ACCOUNTS_URL = "https://accounts.gdgs.jp"
SHORT_URL_BASE = "https://gdgs.jp"
IDP_URL = "https://accounts.gdgs.jp"
IDP_CLIENT_ID = "tinyurl"
DOMAINS_ENABLED = "true"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gdgjp-tinyurl-db"
database_id = "923fde34-1bba-43e4-89c1-cf1e99881e93"
migrations_dir = "./migrations"

[[analytics_engine_datasets]]
binding = "CLICKS_AE"
dataset = "tinyurl_clicks"

[[services]]
binding = "IMG_UPLOAD"
service = "gdgjp-img"
entrypoint = "ImageUploadService"

[[services]]
binding = "IMG_HTTP"
service = "gdgjp-img"

[[routes]]
pattern = "url.gdgs.jp/*"
zone_name = "gdgs.jp"

[[routes]]
pattern = "gdgs.jp/*"
zone_name = "gdgs.jp"

[[routes]]
pattern = "go.gdgs.jp/*"
zone_name = "gdgs.jp"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
