-- Schema dump for @gdgjp/wiki
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE IF NOT EXISTS "user" (
  "id"                        TEXT NOT NULL PRIMARY KEY,
  "name"                      TEXT NOT NULL,
  "email"                     TEXT NOT NULL UNIQUE,
  "image"                     TEXT,
  "created_at"                 INTEGER NOT NULL,
  "updated_at"                 INTEGER NOT NULL,
  -- additionalFields
  "is_admin" INTEGER NOT NULL DEFAULT 0, oidc_issuer TEXT, oidc_subject TEXT);
CREATE TABLE IF NOT EXISTS "chapters" (
  "id"          TEXT NOT NULL PRIMARY KEY,
  "name_ja"     TEXT NOT NULL,
  "name_en"     TEXT NOT NULL,
  "university"  TEXT NOT NULL,
  "region"      TEXT NOT NULL,
  "created_at"  INTEGER NOT NULL DEFAULT (unixepoch())
, abbreviation TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS "tags" (
  "slug"        TEXT NOT NULL PRIMARY KEY,
  "label_ja"    TEXT NOT NULL,
  "label_en"    TEXT NOT NULL,
  "color"       TEXT NOT NULL,
  "page_count"  INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "ingestion_sessions" (
  "id"            TEXT NOT NULL PRIMARY KEY,
  "user_id"       TEXT NOT NULL,
  "status"        TEXT NOT NULL DEFAULT 'pending',
  "inputs_json"   TEXT NOT NULL,
  "ai_draft_json" TEXT,
  "error_message" TEXT,
  "created_at"    INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"    INTEGER NOT NULL DEFAULT (unixepoch())
, "phase_message" TEXT, notified_at INTEGER, "workflow_id" TEXT, "access_context_json" TEXT, "context_manifest_json" TEXT);
CREATE TABLE IF NOT EXISTS "page_tags" (
  "page_id"   TEXT NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "tag_slug"  TEXT NOT NULL REFERENCES "tags"("slug") ON DELETE CASCADE,
  PRIMARY KEY ("page_id", "tag_slug")
);
CREATE TABLE IF NOT EXISTS "page_attachments" (
  "id"          TEXT NOT NULL PRIMARY KEY,
  "page_id"     TEXT NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "r2_key"      TEXT NOT NULL,
  "file_name"   TEXT NOT NULL,
  "mime_type"   TEXT NOT NULL,
  "created_at"  INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "page_versions" (
  "id"          TEXT NOT NULL PRIMARY KEY,
  "page_id"     TEXT NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "content_ja"  TEXT NOT NULL,
  "content_en"  TEXT NOT NULL,
  "title_ja"    TEXT NOT NULL,
  "title_en"    TEXT NOT NULL,
  "edited_by"   TEXT NOT NULL,
  "saved_at"    INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE VIRTUAL TABLE pages_fts USING fts5(
  page_id  UNINDEXED,
  title_ja,
  title_en,
  summary_ja,
  summary_en,
  tags_text,
  tokenize = 'unicode61'
)
/* pages_fts(page_id,title_ja,title_en,summary_ja,summary_en,tags_text) */;
CREATE TABLE IF NOT EXISTS 'pages_fts_data'(id INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'pages_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS 'pages_fts_content'(id INTEGER PRIMARY KEY, c0, c1, c2, c3, c4, c5);
CREATE TABLE IF NOT EXISTS 'pages_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE IF NOT EXISTS 'pages_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
CREATE TRIGGER page_tags_fts_insert AFTER INSERT ON page_tags BEGIN
  UPDATE pages_fts
  SET tags_text = (
    SELECT COALESCE(GROUP_CONCAT(t.label_ja || ' ' || t.label_en, ' '), '')
    FROM page_tags pt
    JOIN tags t ON t.slug = pt.tag_slug
    WHERE pt.page_id = new.page_id
  )
  WHERE page_id = new.page_id;
END;
CREATE TRIGGER page_tags_fts_delete AFTER DELETE ON page_tags BEGIN
  UPDATE pages_fts
  SET tags_text = (
    SELECT COALESCE(GROUP_CONCAT(t.label_ja || ' ' || t.label_en, ' '), '')
    FROM page_tags pt
    JOIN tags t ON t.slug = pt.tag_slug
    WHERE pt.page_id = old.page_id
  )
  WHERE page_id = old.page_id;
END;
CREATE INDEX idx_page_tags_page        ON page_tags (page_id);
CREATE INDEX idx_page_tags_tag         ON page_tags (tag_slug);
CREATE INDEX idx_page_versions_page    ON page_versions (page_id, saved_at DESC);
CREATE INDEX idx_ingestion_sessions_user ON ingestion_sessions (user_id);
CREATE TABLE IF NOT EXISTS "google_drive_tokens" (
  "user_id"       TEXT NOT NULL PRIMARY KEY REFERENCES "user"("id") ON DELETE CASCADE,
  "access_token"  TEXT NOT NULL,
  "refresh_token" TEXT,
  "expires_at"    INTEGER NOT NULL,
  "updated_at"    INTEGER NOT NULL DEFAULT (unixepoch())
, "granted_scopes" TEXT);
CREATE VIRTUAL TABLE pages_fts_trigram USING fts5(
  page_id  UNINDEXED,
  title_ja,
  title_en,
  summary_ja,
  summary_en,
  tags_text,
  tokenize = 'trigram'
)
/* pages_fts_trigram(page_id,title_ja,title_en,summary_ja,summary_en,tags_text) */;
CREATE TABLE IF NOT EXISTS 'pages_fts_trigram_data'(id INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'pages_fts_trigram_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS 'pages_fts_trigram_content'(id INTEGER PRIMARY KEY, c0, c1, c2, c3, c4, c5);
CREATE TABLE IF NOT EXISTS 'pages_fts_trigram_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE IF NOT EXISTS 'pages_fts_trigram_config'(k PRIMARY KEY, v) WITHOUT ROWID;
CREATE TRIGGER page_tags_fts_trigram_insert AFTER INSERT ON page_tags BEGIN
  UPDATE pages_fts_trigram
  SET tags_text = (
    SELECT COALESCE(GROUP_CONCAT(t.label_ja || ' ' || t.label_en, ' '), '')
    FROM page_tags pt JOIN tags t ON t.slug = pt.tag_slug
    WHERE pt.page_id = new.page_id
  )
  WHERE page_id = new.page_id;
END;
CREATE TRIGGER page_tags_fts_trigram_delete AFTER DELETE ON page_tags BEGIN
  UPDATE pages_fts_trigram
  SET tags_text = (
    SELECT COALESCE(GROUP_CONCAT(t.label_ja || ' ' || t.label_en, ' '), '')
    FROM page_tags pt JOIN tags t ON t.slug = pt.tag_slug
    WHERE pt.page_id = old.page_id
  )
  WHERE page_id = old.page_id;
END;
CREATE TABLE IF NOT EXISTS "notifications" (
  "id"         TEXT NOT NULL PRIMARY KEY,
  "user_id"    TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "type"       TEXT NOT NULL,
  "title_ja"   TEXT NOT NULL,
  "title_en"   TEXT NOT NULL,
  "ref_id"     TEXT,
  "ref_url"    TEXT,
  "read_at"    INTEGER,
  "emailed_at" INTEGER,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX "idx_notifications_user_unread"
  ON "notifications" ("user_id", "read_at");
CREATE INDEX "idx_notifications_user_created_at"
  ON "notifications" ("user_id", "created_at");
CREATE TABLE IF NOT EXISTS "page_favorites" (
  "user_id"    TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "page_id"    TEXT NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY ("user_id", "page_id")
);
CREATE INDEX "idx_page_favorites_user"
  ON "page_favorites" ("user_id");
CREATE TABLE page_sources (
  id TEXT PRIMARY KEY,
  page_id TEXT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
, "source_id" TEXT REFERENCES "sources"("id") ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS "page_views" (
  "user_id"   TEXT    NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "page_id"   TEXT    NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "viewed_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY ("user_id", "page_id")
);
CREATE INDEX "idx_page_views_user_viewed_at"
  ON "page_views" ("user_id", "viewed_at" DESC);
CREATE TABLE IF NOT EXISTS "page_comments" (
  "id"           TEXT    NOT NULL PRIMARY KEY,
  "page_id"      TEXT    NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "author_id"    TEXT    NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "parent_id"    TEXT    REFERENCES "page_comments"("id") ON DELETE CASCADE,
  "content_json" TEXT    NOT NULL,
  "deleted_at"   INTEGER,
  "created_at"   INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"   INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX "idx_page_comments_page_id"
  ON "page_comments" ("page_id", "created_at");
CREATE INDEX "idx_page_comments_parent_id"
  ON "page_comments" ("parent_id");
CREATE TABLE IF NOT EXISTS "comment_reactions" (
  "comment_id" TEXT    NOT NULL REFERENCES "page_comments"("id") ON DELETE CASCADE,
  "user_id"    TEXT    NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "emoji"      TEXT    NOT NULL,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY ("comment_id", "user_id", "emoji")
);
CREATE TABLE page_embedding_status (
  page_id TEXT PRIMARY KEY REFERENCES pages(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  -- 'pending' | 'indexed' | 'error'
  chunk_count INTEGER NOT NULL DEFAULT 0,
  content_hash TEXT,
  last_indexed_at INTEGER,
  error_message TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "fcm_tokens" (
  "token"        TEXT NOT NULL PRIMARY KEY,
  "user_id"      TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "device_label" TEXT,
  "created_at"   INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"   INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX "idx_fcm_tokens_user_id" ON "fcm_tokens" ("user_id");
CREATE TABLE `task_lists` (
  `page_id` text PRIMARY KEY NOT NULL,
  `next_task_number` integer NOT NULL DEFAULT 1,
  FOREIGN KEY (`page_id`) REFERENCES `pages`(`id`) ON DELETE CASCADE
);
CREATE TABLE `task_list_teams` (
  `id` text PRIMARY KEY NOT NULL,
  `task_list_id` text NOT NULL,
  `name` text NOT NULL,
  `color` text DEFAULT '#6b7280',
  `sort_order` integer DEFAULT 0,
  FOREIGN KEY (`task_list_id`) REFERENCES `task_lists`(`page_id`) ON DELETE CASCADE
);
CREATE TABLE `tasks` (
  `id` text PRIMARY KEY NOT NULL,
  `task_list_id` text NOT NULL,
  `number` integer NOT NULL,
  `title` text NOT NULL,
  `description` text NOT NULL DEFAULT '',
  `status` text NOT NULL DEFAULT 'todo',
  `type` text NOT NULL DEFAULT 'task',
  `due_date` text,
  `assignee_id` text,
  `team_id` text,
  `created_by` text NOT NULL,
  `sort_order` integer NOT NULL DEFAULT 0,
  `created_at` integer NOT NULL DEFAULT (unixepoch()),
  `updated_at` integer NOT NULL DEFAULT (unixepoch()), `assignee_name` text,
  FOREIGN KEY (`task_list_id`) REFERENCES `task_lists`(`page_id`) ON DELETE CASCADE,
  FOREIGN KEY (`assignee_id`) REFERENCES `user`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`team_id`) REFERENCES `task_list_teams`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON DELETE CASCADE
);
CREATE TABLE `task_dependencies` (
  `task_id` text NOT NULL,
  `depends_on_task_id` text NOT NULL,
  PRIMARY KEY (`task_id`, `depends_on_task_id`),
  FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`depends_on_task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
  CHECK (`task_id` <> `depends_on_task_id`)
);
CREATE INDEX `idx_tasks_task_list_id` ON `tasks` (`task_list_id`);
CREATE INDEX `idx_tasks_assignee_id` ON `tasks` (`assignee_id`);
CREATE INDEX `idx_tasks_status` ON `tasks` (`task_list_id`, `status`);
CREATE INDEX `idx_tasks_due_date` ON `tasks` (`task_list_id`, `due_date`);
CREATE UNIQUE INDEX `idx_tasks_number` ON `tasks` (`task_list_id`, `number`);
CREATE TRIGGER `tasks_assignee_exclusive_insert`
BEFORE INSERT ON `tasks`
FOR EACH ROW
WHEN NEW.`assignee_id` IS NOT NULL AND NEW.`assignee_name` IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'tasks: assignee_id and assignee_name cannot both be set');
END;
CREATE TRIGGER `tasks_assignee_exclusive_update`
BEFORE UPDATE ON `tasks`
FOR EACH ROW
WHEN NEW.`assignee_id` IS NOT NULL AND NEW.`assignee_name` IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'tasks: assignee_id and assignee_name cannot both be set');
END;
CREATE TABLE IF NOT EXISTS "discord_guild_settings" (
  "guild_id"            TEXT NOT NULL PRIMARY KEY,
  "chapter_id"          TEXT NOT NULL UNIQUE REFERENCES "chapters"("id") ON DELETE CASCADE,
  "reminder_channel_id" TEXT NOT NULL,
  "enabled"             INTEGER NOT NULL DEFAULT 1,
  "created_at"          INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"          INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX "idx_discord_guild_settings_chapter_id"
  ON "discord_guild_settings" ("chapter_id");
CREATE TABLE user_preferences (
  user_id                    TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
  preferred_ui_language      TEXT NOT NULL DEFAULT 'ja',
  preferred_content_language TEXT NOT NULL DEFAULT 'ja',
  discord_id                 TEXT UNIQUE
);
CREATE UNIQUE INDEX user_oidc_identity_idx ON "user" (oidc_issuer, oidc_subject);
CREATE TABLE oidc_session (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  issuer TEXT NOT NULL,
  subject TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  id_token TEXT NOT NULL,
  access_token_expires_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX oidc_session_user_idx ON oidc_session (user_id);
CREATE TABLE IF NOT EXISTS "page_access" (
  "id"            TEXT NOT NULL PRIMARY KEY,
  "page_id"       TEXT NOT NULL REFERENCES "pages"("id") ON DELETE CASCADE,
  "subject_type"  TEXT NOT NULL CHECK ("subject_type" IN ('email', 'chapter')),
  "subject_key"   TEXT NOT NULL,
  "subject_label" TEXT NOT NULL,
  "user_id"       TEXT REFERENCES "user"("id") ON DELETE SET NULL,
  "role"          TEXT NOT NULL DEFAULT 'viewer' CHECK ("role" IN ('viewer', 'commenter', 'editor')),
  "granted_by"    TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "created_at"    INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"    INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE ("page_id", "subject_type", "subject_key")
);
CREATE INDEX "idx_page_access_page_id" ON "page_access" ("page_id");
CREATE INDEX "idx_page_access_user_id" ON "page_access" ("user_id");
CREATE INDEX "idx_page_access_subject" ON "page_access" ("subject_type", "subject_key");
CREATE TABLE content_backfills (
  name TEXT NOT NULL PRIMARY KEY,
  completed_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "google_document_imports" (
  "document_id"      TEXT NOT NULL PRIMARY KEY,
  "root_page_id"     TEXT NOT NULL UNIQUE REFERENCES "pages"("id") ON DELETE CASCADE,
  "imported_by"      TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "status"           TEXT NOT NULL DEFAULT 'ready'
                     CHECK ("status" IN ('ready', 'syncing', 'failed')),
  "error_message"    TEXT,
  "last_imported_at" INTEGER,
  "created_at"       INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"       INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "google_document_import_nodes" (
  "document_id"           TEXT NOT NULL REFERENCES "google_document_imports"("document_id") ON DELETE CASCADE,
  "source_node_id"        TEXT NOT NULL,
  "page_id"               TEXT NOT NULL UNIQUE REFERENCES "pages"("id") ON DELETE CASCADE,
  "source_parent_node_id" TEXT,
  "source_kind"           TEXT NOT NULL CHECK ("source_kind" IN ('document', 'tab')),
  "sort_order"            INTEGER NOT NULL DEFAULT 0,
  "status"                TEXT NOT NULL DEFAULT 'active'
                           CHECK ("status" IN ('active', 'archived')),
  "created_at"            INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"            INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY ("document_id", "source_node_id")
);
CREATE INDEX "idx_google_document_import_nodes_document_parent"
  ON "google_document_import_nodes" ("document_id", "source_parent_node_id", "sort_order");
CREATE INDEX "idx_google_document_import_nodes_document_status"
  ON "google_document_import_nodes" ("document_id", "status");
CREATE TABLE IF NOT EXISTS "google_document_import_jobs" (
  "id"               TEXT NOT NULL PRIMARY KEY,
  "document_id"      TEXT NOT NULL UNIQUE,
  "requested_by"     TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "status"           TEXT NOT NULL DEFAULT 'queued'
                     CHECK ("status" IN ('queued', 'running', 'completed', 'failed')),
  "total_nodes"      INTEGER NOT NULL DEFAULT 0,
  "completed_nodes"  INTEGER NOT NULL DEFAULT 0,
  "total_images"     INTEGER NOT NULL DEFAULT 0,
  "completed_images" INTEGER NOT NULL DEFAULT 0,
  "warning_count"    INTEGER NOT NULL DEFAULT 0,
  "error_message"    TEXT,
  "created_at"       INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"       INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "pages" (
  id TEXT NOT NULL PRIMARY KEY,
  title_ja TEXT NOT NULL,
  title_en TEXT NOT NULL DEFAULT '',
  slug TEXT NOT NULL UNIQUE,
  content_ja TEXT NOT NULL,
  content_en TEXT NOT NULL DEFAULT '',
  translation_status_ja TEXT NOT NULL DEFAULT 'human',
  translation_status_en TEXT NOT NULL DEFAULT 'missing',
  summary_ja TEXT NOT NULL DEFAULT '',
  summary_en TEXT NOT NULL DEFAULT '',
  parent_id TEXT REFERENCES pages(id) ON DELETE SET NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'archived')),
  page_type TEXT,
  page_metadata TEXT,
  ingestion_session_id TEXT REFERENCES ingestion_sessions(id) ON DELETE SET NULL,
  actionability_score INTEGER,
  author_id TEXT NOT NULL,
  last_edited_by TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  visibility TEXT NOT NULL DEFAULT 'restricted',
  chapter_id TEXT REFERENCES chapters(id) ON DELETE SET NULL,
  general_role TEXT NOT NULL DEFAULT 'viewer'
    CHECK (general_role IN ('viewer', 'commenter', 'editor')),
  sync_revision INTEGER NOT NULL DEFAULT 1
, "origin" TEXT NOT NULL DEFAULT 'human'
  CHECK ("origin" IN ('human', 'agent')), acl_synced_with_parent INTEGER NOT NULL DEFAULT 1, acl_source_ids TEXT NOT NULL DEFAULT '[]');
CREATE INDEX idx_pages_status_updated ON pages (status, updated_at DESC);
CREATE INDEX idx_pages_parent_order ON pages (parent_id, sort_order ASC);
CREATE INDEX idx_pages_author ON pages (author_id, updated_at DESC);
CREATE INDEX idx_pages_slug ON pages (slug);
CREATE INDEX idx_pages_visibility ON pages (visibility);
CREATE INDEX idx_pages_chapter_id ON pages (chapter_id);
CREATE TRIGGER pages_fts_insert AFTER INSERT ON pages BEGIN
  INSERT INTO pages_fts(page_id, title_ja, title_en, summary_ja, summary_en, tags_text)
  VALUES (new.id, new.title_ja, new.title_en, new.summary_ja, new.summary_en, '');
END;
CREATE TRIGGER pages_fts_update AFTER UPDATE ON pages BEGIN
  UPDATE pages_fts
  SET title_ja = new.title_ja, title_en = new.title_en, summary_ja = new.summary_ja,
      summary_en = new.summary_en
  WHERE page_id = new.id;
END;
CREATE TRIGGER pages_fts_delete AFTER DELETE ON pages BEGIN
  DELETE FROM pages_fts WHERE page_id = old.id;
END;
CREATE TRIGGER pages_fts_trigram_insert AFTER INSERT ON pages BEGIN
  INSERT INTO pages_fts_trigram(page_id, title_ja, title_en, summary_ja, summary_en, tags_text)
  VALUES (new.id, new.title_ja, new.title_en, new.summary_ja, new.summary_en, '');
END;
CREATE TRIGGER pages_fts_trigram_update AFTER UPDATE ON pages BEGIN
  UPDATE pages_fts_trigram
  SET title_ja = new.title_ja, title_en = new.title_en, summary_ja = new.summary_ja,
      summary_en = new.summary_en
  WHERE page_id = new.id;
END;
CREATE TRIGGER pages_fts_trigram_delete AFTER DELETE ON pages BEGIN
  DELETE FROM pages_fts_trigram WHERE page_id = old.id;
END;
CREATE TRIGGER trg_page_embedding_insert
AFTER INSERT ON pages WHEN NEW.status = 'published'
BEGIN
  INSERT OR IGNORE INTO page_embedding_status (page_id, status) VALUES (NEW.id, 'pending');
END;
CREATE TRIGGER trg_page_embedding_update
AFTER UPDATE ON pages WHEN NEW.status = 'published'
BEGIN
  INSERT INTO page_embedding_status (page_id, status, updated_at)
  VALUES (NEW.id, 'pending', unixepoch())
  ON CONFLICT(page_id) DO UPDATE SET status = 'pending', updated_at = unixepoch();
END;
CREATE TRIGGER pages_sync_revision_update
AFTER UPDATE ON pages WHEN NEW.sync_revision = OLD.sync_revision
BEGIN
  UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.id;
END;
CREATE TRIGGER page_tags_sync_revision_insert AFTER INSERT ON page_tags
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_tags_sync_revision_delete AFTER DELETE ON page_tags
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = OLD.page_id; END;
CREATE TRIGGER page_sources_sync_revision_insert AFTER INSERT ON page_sources
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_sources_sync_revision_update AFTER UPDATE ON page_sources
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_sources_sync_revision_delete AFTER DELETE ON page_sources
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = OLD.page_id; END;
CREATE TRIGGER page_attachments_sync_revision_insert AFTER INSERT ON page_attachments
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_attachments_sync_revision_update AFTER UPDATE ON page_attachments
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_attachments_sync_revision_delete AFTER DELETE ON page_attachments
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = OLD.page_id; END;
CREATE TRIGGER page_access_sync_revision_insert AFTER INSERT ON page_access
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_access_sync_revision_update AFTER UPDATE ON page_access
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = NEW.page_id; END;
CREATE TRIGGER page_access_sync_revision_delete AFTER DELETE ON page_access
BEGIN UPDATE pages SET sync_revision = sync_revision + 1 WHERE id = OLD.page_id; END;
CREATE TABLE IF NOT EXISTS "source_assets" (
  "id"                 TEXT NOT NULL PRIMARY KEY,
  "source_document_id" TEXT NOT NULL REFERENCES "source_documents"("id") ON DELETE CASCADE,
  "path"               TEXT NOT NULL,
  "r2_key"             TEXT NOT NULL,
  "mime_type"          TEXT NOT NULL,
  "byte_size"          INTEGER NOT NULL,
  "content_hash"       TEXT NOT NULL
);
CREATE INDEX "idx_source_assets_source_document_id"
  ON "source_assets" ("source_document_id");
CREATE INDEX "idx_pages_origin" ON "pages" ("origin");
CREATE INDEX "idx_page_sources_source_id" ON "page_sources" ("source_id");
CREATE TABLE IF NOT EXISTS "wiki_agent_instructions" (
  "id" INTEGER NOT NULL PRIMARY KEY CHECK ("id" = 1),
  "content" TEXT NOT NULL,
  "content_hash" TEXT NOT NULL,
  "updated_by" TEXT NOT NULL REFERENCES "user"("id"),
  "updated_at" INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "source_import_runs" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "source_id" TEXT NOT NULL UNIQUE REFERENCES "sources"("id") ON DELETE CASCADE,
  "kind" TEXT NOT NULL CHECK ("kind" IN ('google-chat-space', 'google-drive', 'website')),
  "fetch_attempt_id" TEXT NOT NULL,
  "phase" TEXT NOT NULL DEFAULT 'start',
  "since_cursor" TEXT,
  "progress" TEXT NOT NULL DEFAULT '{}',
  "consecutive_failures" INTEGER NOT NULL DEFAULT 0,
  "error_message" TEXT,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at" INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "source_documents" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "source_id" TEXT NOT NULL REFERENCES "sources"("id") ON DELETE CASCADE,
  "path" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "r2_key" TEXT NOT NULL,
  "content_hash" TEXT NOT NULL,
  "media_type" TEXT NOT NULL DEFAULT 'text/markdown',
  "captured_at" INTEGER NOT NULL,
  "cursor" TEXT,
  "metadata" TEXT,
  "status" TEXT NOT NULL DEFAULT 'ready'
    CHECK ("status" IN ('ready', 'error', 'archived')),
  UNIQUE ("source_id", "path")
);
CREATE INDEX "idx_source_documents_source_id" ON "source_documents" ("source_id");
CREATE TABLE IF NOT EXISTS "google_chat_sender_profiles" (
  "resource_name" TEXT NOT NULL PRIMARY KEY,
  "display_name" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at" INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE TABLE IF NOT EXISTS "google_chat_sender_samples" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "resource_name" TEXT NOT NULL,
  "source_id" TEXT NOT NULL REFERENCES "sources"("id") ON DELETE CASCADE,
  "message_name" TEXT NOT NULL,
  "message_text" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE (resource_name, source_id, message_name)
);
CREATE INDEX "idx_google_chat_sender_samples_resource_created"
  ON "google_chat_sender_samples" ("resource_name", "created_at" DESC);
CREATE INDEX idx_pages_parent_acl_sync
  ON pages (parent_id, acl_synced_with_parent);
CREATE TABLE IF NOT EXISTS "sources" (
  "id"               TEXT NOT NULL PRIMARY KEY,
  "kind"             TEXT NOT NULL
                     CHECK ("kind" IN (
                       'google-doc',
                       'google-sheet',
                       'google-slides',
                       'google-chat-space',
                       'website',
                       'upload',
                       'text'
                     )),
  "external_id"      TEXT,
  "url"              TEXT NOT NULL,
  "title"            TEXT NOT NULL,
  "chapter_id"       TEXT,
  "added_by"         TEXT NOT NULL REFERENCES "user"("id"),
  "status"           TEXT NOT NULL DEFAULT 'pending'
                     CHECK ("status" IN ('pending', 'fetching', 'ready', 'error', 'archived')),
  "refresh_policy"   TEXT NOT NULL DEFAULT 'manual'
                     CHECK ("refresh_policy" IN ('manual', 'daily', 'weekly')),
  "last_fetched_at"  INTEGER,
  "error_message"    TEXT,
  "created_at"       INTEGER NOT NULL DEFAULT (unixepoch()),
  "updated_at"       INTEGER NOT NULL DEFAULT (unixepoch()),
  "fetch_attempt_id" TEXT,
  "visibility"       TEXT NOT NULL DEFAULT 'member'
                     CHECK ("visibility" IN (
                       'private',
                       'member',
                       'organizer',
                       'chapter-member',
                       'chapter-organizer'
                     )),
  CHECK (
    ("visibility" IN ('chapter-member', 'chapter-organizer')) = ("chapter_id" IS NOT NULL)
  )
);
CREATE INDEX "idx_sources_status" ON "sources" ("status");
CREATE INDEX "idx_sources_chapter_id" ON "sources" ("chapter_id");
CREATE INDEX "idx_sources_added_by" ON "sources" ("added_by");
CREATE INDEX "idx_sources_refresh_policy" ON "sources" ("refresh_policy", "status");
CREATE INDEX "idx_sources_visibility" ON "sources" ("visibility", "chapter_id");
