-- Schema dump for @gdgjp/scheduler
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE _migrations_seed (
  id INTEGER PRIMARY KEY
);
CREATE TABLE events (
  id            TEXT NOT NULL PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  owner_user_id TEXT,
  created_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at    INTEGER
, slot_minutes INTEGER NOT NULL DEFAULT 60);
CREATE INDEX events_owner_user_id_idx
  ON events (owner_user_id) WHERE owner_user_id IS NOT NULL;
CREATE TABLE event_slots (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id    TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time  TEXT NOT NULL CHECK (length(start_time) = 5),
  UNIQUE (event_id, day_of_week, start_time)
);
CREATE INDEX event_slots_event_id_idx ON event_slots (event_id);
CREATE TABLE event_participants (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id        TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id         TEXT,
  display_name    TEXT NOT NULL,
  edit_token_hash TEXT,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX event_participants_event_id_idx ON event_participants (event_id);
CREATE UNIQUE INDEX event_participants_user_unique
  ON event_participants (event_id, user_id) WHERE user_id IS NOT NULL;
CREATE TABLE event_availabilities (
  participant_id INTEGER NOT NULL REFERENCES event_participants(id) ON DELETE CASCADE,
  slot_id        INTEGER NOT NULL REFERENCES event_slots(id) ON DELETE CASCADE,
  PRIMARY KEY (participant_id, slot_id)
);
CREATE INDEX event_availabilities_slot_id_idx ON event_availabilities (slot_id);
CREATE TABLE IF NOT EXISTS "user" (
  "id"            TEXT NOT NULL PRIMARY KEY,
  "name"          TEXT NOT NULL,
  "email"         TEXT NOT NULL UNIQUE,
  "emailVerified" INTEGER NOT NULL,
  "image"         TEXT,
  "createdAt"     TEXT NOT NULL,
  "updatedAt"     TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "session" (
  "id"        TEXT NOT NULL PRIMARY KEY,
  "expiresAt" TEXT NOT NULL,
  "token"     TEXT NOT NULL UNIQUE,
  "createdAt" TEXT NOT NULL,
  "updatedAt" TEXT NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId"    TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "account" (
  "id"                     TEXT NOT NULL PRIMARY KEY,
  "accountId"              TEXT NOT NULL,
  "providerId"             TEXT NOT NULL,
  "userId"                 TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "accessToken"            TEXT,
  "refreshToken"           TEXT,
  "idToken"                TEXT,
  "accessTokenExpiresAt"   TEXT,
  "refreshTokenExpiresAt"  TEXT,
  "scope"                  TEXT,
  "createdAt"              TEXT NOT NULL,
  "updatedAt"              TEXT NOT NULL
);
CREATE INDEX "session_userId_idx"          ON "session" ("userId");
CREATE INDEX "account_userId_idx"          ON "account" ("userId");
CREATE TABLE IF NOT EXISTS "verification" (
  "id"         TEXT NOT NULL PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value"      TEXT NOT NULL,
  "expiresAt"  TEXT NOT NULL,
  "createdAt"  TEXT NOT NULL,
  "updatedAt"  TEXT NOT NULL
);
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");
