/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cli/wiki/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wiki pages visible to the CLI token (agent origin only) */
        get: operations["getWikiSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically create, update, or archive Wiki pages */
        post: operations["syncWiki"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        /** Download an attachment visible to the CLI token */
        get: operations["downloadWikiAttachment"];
        /** Replace bytes for an attachment allocated by sync */
        put: operations["uploadWikiAttachment"];
        post?: never;
        /** Delete an attachment */
        delete: operations["deleteWikiAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get raw-source manifest visible to the CLI token */
        get: operations["getWikiSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/sources/{documentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download raw content for a manifest document id */
        get: operations["getWikiSourceContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/agents-md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the centrally managed AGENTS.md for wiki clones */
        get: operations["getWikiAgentsMd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/ls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a Wiki workspace directory visible to the Bearer token */
        get: operations["agentLs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/cat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a Wiki workspace page visible to the Bearer token */
        get: operations["agentCat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Wiki pages visible to the Bearer token */
        get: operations["agentSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a source for ingestion as the Bearer token's user */
        post: operations["agentCreateSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or replace a filed query answer under the answers namespace */
        post: operations["agentCreateNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically append a query log entry */
        post: operations["agentAppendLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AGENTS.md slice for the query filing pass */
        get: operations["agentGetInstructions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Snapshot: {
            /** @enum {integer} */
            version: 1;
            pages: components["schemas"]["SnapshotPage"][];
            agentsMd: components["schemas"]["AgentInstructions"];
        };
        AgentInstructions: {
            content: string;
            contentHash: string;
        };
        SyncRequest: {
            operations?: (components["schemas"]["UpsertOperation"] | components["schemas"]["ArchiveOperation"])[];
            agentsMd?: components["schemas"]["AgentInstructionsUpdate"];
        };
        SyncResult: {
            /** @enum {boolean} */
            ok: true;
            pages: components["schemas"]["SyncResultPage"][];
        };
        SourcesManifest: {
            /** @enum {integer} */
            version: 1;
            documents: components["schemas"]["SourcesManifestEntry"][];
        };
        AgentLsEntry: {
            name: string;
            /** @description Absolute workspace path. */
            path: string;
            readable: boolean;
            hasChildren: boolean | "unknown";
            title?: string;
        };
        AgentLsResult: {
            path: string;
            entries: components["schemas"]["AgentLsEntry"][];
            nextCursor: string | null;
            truncated: boolean;
        };
        AgentCatResult: {
            path: string;
            content: string;
            nextCursor: string | null;
            truncated: boolean;
        };
        AgentSearchMatch: {
            path: string;
            title: string;
            snippet?: string;
        };
        AgentSearchResult: {
            matches: components["schemas"]["AgentSearchMatch"][];
            nextCursor: string | null;
            truncated: boolean;
        };
        AgentCreateSourceRequest: {
            /** Format: uri */
            url: string;
            /** @enum {string} */
            visibility: "private" | "member" | "organizer" | "chapter-member" | "chapter-organizer";
            /** @description Chapter id when visibility is chapter-member or chapter-organizer. */
            chapter?: string;
            /** @enum {string} */
            refreshPolicy?: "manual" | "daily" | "weekly";
        };
        AgentSource: {
            id: string;
            kind: string;
            url: string;
            title: string;
            chapterId: string | null;
            /** @enum {string} */
            visibility: "private" | "member" | "organizer" | "chapter-member" | "chapter-organizer";
            /** @enum {string} */
            status: "pending";
            /** @enum {string} */
            refreshPolicy: "manual" | "daily" | "weekly";
        };
        AgentCreateNoteRequest: {
            slug: string;
            title: string;
            summary: string;
            content: string;
            citedPaths: string[];
            replaceId?: string;
        };
        AgentNote: {
            id: string;
            slug: string;
            path: string;
            /** Format: uri */
            pageUrl: string;
            created: boolean;
        };
        AgentLogRequest: {
            subject: string;
            lines: string[];
        };
        AgentInstructionsSlice: {
            /** @enum {string} */
            profile: "query";
            content: string;
            contentHash: string;
        };
        Error: {
            error: string;
            id?: string;
            message?: string;
        };
        Language: {
            title: string;
            summary: string;
            /** @enum {string} */
            translationStatus: "human" | "ai" | "missing";
            content: string;
        };
        AccessEntry: {
            id?: string;
            /** @enum {string} */
            subjectType: "email" | "chapter";
            subjectKey: string;
            subjectLabel: string;
            /** @enum {string} */
            role: "viewer" | "commenter" | "editor";
        };
        Source: {
            id?: string;
            url?: string;
            title: string;
            sourceId?: string | null;
        };
        Attachment: {
            id?: string;
            r2Key?: string;
            fileName: string;
            mimeType: string;
            downloadUrl?: string;
        };
        PageMeta: {
            pageType: string | null;
            pageMetadata: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            visibility: "restricted" | "unlisted" | "public";
            /** @enum {string} */
            generalRole: "viewer" | "commenter" | "editor";
            chapterId: string | null;
            tags: string[];
            access: components["schemas"]["AccessEntry"][];
            sources: components["schemas"]["Source"][];
            attachments: components["schemas"]["Attachment"][];
        };
        Page: {
            /** @description Client-stable ID for updates or for referencing a new page within the same atomic sync. */
            id?: string;
            slug: string;
            parentId: string | null;
            sortOrder: number;
            revision?: number;
            ja?: components["schemas"]["Language"];
            en?: components["schemas"]["Language"];
            meta: components["schemas"]["PageMeta"];
        };
        SnapshotPage: components["schemas"]["Page"] & {
            id: string;
            revision: number;
            pageType: string | null;
            pageMetadata: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            visibility: "restricted" | "unlisted" | "public";
            /** @enum {string} */
            generalRole: "viewer" | "commenter" | "editor";
            chapterId: string | null;
            /** @description True when the caller cannot read every ACL span and span bodies were removed from the returned locale content. */
            aclRedacted?: boolean;
            tags: string[];
            access: components["schemas"]["AccessEntry"][];
            sources: components["schemas"]["Source"][];
            attachments: components["schemas"]["Attachment"][];
        };
        UpsertOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "upsert";
            expectedRevision?: number;
            page: components["schemas"]["Page"];
        };
        ArchiveOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "archive";
            id: string;
            expectedRevision: number;
        };
        AgentInstructionsUpdate: {
            content: string;
            expectedContentHash: string;
        };
        SyncResultPage: {
            id: string;
            slug: string;
            revision?: number;
            attachmentIds: {
                [key: string]: string;
            };
        };
        RevisionConflict: {
            /** @enum {string} */
            error: "revision_conflict";
            conflicts: {
                id: string;
                revision: number;
            }[];
        };
        Ok: {
            /** @enum {boolean} */
            ok: true;
        };
        SourcesManifestEntry: {
            documentId: string;
            sourceId?: string | null;
            /** @enum {string} */
            kind: "source-document" | "source-asset" | "wiki-human";
            title: string;
            path: string;
            contentHash: string;
            mediaType?: string;
            capturedAt?: number | null;
            /** @description Source visibility for source-document / source-asset entries (private|member|organizer|chapter-member|chapter-organizer). Omitted for wiki-human entries. */
            visibility?: string | null;
        };
    };
    responses: {
        /** @description The access token is missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested page or attachment does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The JSON payload or requested state is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The access token cannot perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation completed successfully. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Ok"];
            };
        };
    };
    parameters: {
        AttachmentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWikiSnapshot: {
        parameters: {
            query?: {
                /** @description Return only the selected locale. Other locale fields are omitted. */
                lang?: "ja" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Wiki snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    syncWiki: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Applied operations and allocated attachment IDs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description One or more page revisions are stale; no operation was applied. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionConflict"];
                };
            };
        };
    };
    downloadWikiAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadWikiAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Attachment exceeds 25 MiB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteWikiAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getWikiSources: {
        parameters: {
            query?: {
                /** @description Locale used when materializing wiki-human manifest entries. */
                lang?: "ja" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getWikiSourceContent: {
        parameters: {
            query?: {
                /** @description Locale used when materializing wiki-human pages. */
                lang?: "ja" | "en";
            };
            header?: never;
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw file bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "application/pdf": string;
                    "text/markdown": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getWikiAgentsMd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AGENTS.md markdown body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    agentLs: {
        parameters: {
            query?: {
                /** @description Absolute workspace path (default `/`). */
                path?: string;
                /** @description Max directory entries (clamped to the workspace limit). */
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing for the caller's authorized view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentLsResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    agentCat: {
        parameters: {
            query: {
                /** @description Absolute workspace path of the page to read. */
                path: string;
                /** @description Max characters to return (clamped to the workspace limit). */
                maxChars?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page content slice for the caller's authorized view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCatResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    agentSearch: {
        parameters: {
            query: {
                /** @description Title/slug/body search query. */
                q: string;
                /** @description Optional absolute path scope. */
                path?: string;
                /** @description Max matches (clamped to the workspace limit). */
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search matches for the caller's authorized view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSearchResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    agentCreateSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreateSourceRequest"];
            };
        };
        responses: {
            /** @description Source registered and fetch enqueued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSource"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    agentCreateNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreateNoteRequest"];
            };
        };
        responses: {
            /** @description Existing answer page replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentNote"];
                };
            };
            /** @description Answer page created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentNote"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Refused without writing: `slug_exists`, `citations_span_access`, `citations_span_chapters`, `chapter_ambiguous`, or — when replacing — `replace_scope_mismatch` (the target's chapter differs from the citation floor) or `replace_target_shared` (the target carries explicit ACL rows). Replacement never moves a page's access scope, because the page_versions row it writes preserves the prior content under the new permissions. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    agentAppendLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentLogRequest"];
            };
        };
        responses: {
            /** @description Log entry appended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Log page unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    agentGetInstructions: {
        parameters: {
            query: {
                profile: "query";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instruction slice for the requested profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInstructionsSlice"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Required AGENTS.md headings are missing or unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
