/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cli/wiki/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Wiki pages visible to the CLI token */
        get: operations["getWikiSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically create, update, or archive Wiki pages */
        post: operations["syncWiki"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/wiki/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        /** Download an attachment visible to the CLI token */
        get: operations["downloadWikiAttachment"];
        /** Replace bytes for an attachment allocated by sync */
        put: operations["uploadWikiAttachment"];
        post?: never;
        /** Delete an attachment */
        delete: operations["deleteWikiAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Snapshot: {
            /** @enum {integer} */
            version: 1;
            pages: components["schemas"]["SnapshotPage"][];
        };
        SyncRequest: {
            operations: (components["schemas"]["UpsertOperation"] | components["schemas"]["ArchiveOperation"])[];
        };
        SyncResult: {
            /** @enum {boolean} */
            ok: true;
            pages: components["schemas"]["SyncResultPage"][];
        };
        Error: {
            error: string;
            id?: string;
            message?: string;
        };
        Language: {
            title: string;
            summary: string;
            /** @enum {string} */
            translationStatus: "human" | "ai" | "missing";
            content: string;
        };
        AccessEntry: {
            id?: string;
            /** @enum {string} */
            subjectType: "email" | "chapter";
            subjectKey: string;
            subjectLabel: string;
            /** @enum {string} */
            role: "viewer" | "commenter" | "editor";
        };
        Source: {
            id?: string;
            /** Format: uri */
            url: string;
            title: string;
        };
        Attachment: {
            id?: string;
            r2Key?: string;
            fileName: string;
            mimeType: string;
            downloadUrl?: string;
        };
        PageMeta: {
            pageType: string | null;
            pageMetadata: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            visibility: "restricted" | "unlisted" | "public";
            /** @enum {string} */
            generalRole: "viewer" | "commenter" | "editor";
            chapterId: string | null;
            tags: string[];
            access: components["schemas"]["AccessEntry"][];
            sources: components["schemas"]["Source"][];
            attachments: components["schemas"]["Attachment"][];
        };
        Page: {
            id?: string;
            slug: string;
            parentId: string | null;
            sortOrder: number;
            revision?: number;
            ja: components["schemas"]["Language"];
            en: components["schemas"]["Language"];
            meta: components["schemas"]["PageMeta"];
        };
        SnapshotPage: components["schemas"]["Page"] & {
            id: string;
            revision: number;
            pageType: string | null;
            pageMetadata: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            visibility: "restricted" | "unlisted" | "public";
            /** @enum {string} */
            generalRole: "viewer" | "commenter" | "editor";
            chapterId: string | null;
            tags: string[];
            access: components["schemas"]["AccessEntry"][];
            sources: components["schemas"]["Source"][];
            attachments: components["schemas"]["Attachment"][];
        };
        UpsertOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "upsert";
            expectedRevision?: number;
            page: components["schemas"]["Page"];
        };
        ArchiveOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "archive";
            id: string;
            expectedRevision: number;
        };
        SyncResultPage: {
            id: string;
            slug: string;
            revision?: number;
            attachmentIds: {
                [key: string]: string;
            };
        };
        RevisionConflict: {
            /** @enum {string} */
            error: "revision_conflict";
            conflicts: {
                id: string;
                revision: number;
            }[];
        };
        Ok: {
            /** @enum {boolean} */
            ok: true;
        };
    };
    responses: {
        /** @description The access token is missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested page or attachment does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The JSON payload or requested state is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The access token cannot perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation completed successfully. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Ok"];
            };
        };
    };
    parameters: {
        AttachmentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWikiSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Wiki snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncWiki: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Applied operations and allocated attachment IDs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description One or more page revisions are stale; no operation was applied. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionConflict"];
                };
            };
        };
    };
    downloadWikiAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadWikiAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Attachment exceeds 25 MiB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteWikiAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
