import { isSuperAdmin } from "@gdgjp/gdg-lib";
import { createFolder, listAccessibleFoldersPage } from "~/features/folders";
import { requireCliActor } from "~/lib/cli-auth.server";
import { cliError, cliJson, cliMethodNotAllowed, parseCliJsonBody } from "~/lib/cli-http.server";
import type { Route } from "./+types/api.cli.v1.folders";
function viewer(auth: { actor: { user: import("@gdgjp/gdg-lib").AuthUser; chapters: { chapterId: number }[] } }) { return { userId: auth.actor.user.id, email: auth.actor.user.email, chapterIds: auth.actor.chapters.map((c) => c.chapterId), isSuperAdmin: isSuperAdmin(auth.actor.user) }; }
function id(raw: string | null) { if (raw === null) return undefined; const n = Number(raw); return Number.isInteger(n) && n > 0 ? n : null; }
function cursor(raw: string | null) { try { const offset = Number(raw ? atob(raw) : 0); return Number.isInteger(offset) && offset >= 0 ? offset : null; } catch { return null; } }
export async function loader(args: Route.LoaderArgs) { const env = args.context.cloudflare.env; const auth = await requireCliActor(env, args.request); if (!auth.ok) return auth.response; const url = new URL(args.request.url); const parent = id(url.searchParams.get("parentFolderId")); const rawLimit = url.searchParams.get("limit"); const limit = rawLimit === null ? 50 : Number(rawLimit); const offset = cursor(url.searchParams.get("cursor")); if (parent === null || offset === null || !Number.isInteger(limit) || limit < 1 || limit > 100) return cliError("invalid_request", 400); return cliJson(await listAccessibleFoldersPage(env.DB, viewer(auth), { ...(parent === undefined ? {} : { parentFolderId: parent }), limit, offset })); }
export async function action(args: Route.ActionArgs) { if (args.request.method !== "POST") return cliMethodNotAllowed(); const env = args.context.cloudflare.env; const auth = await requireCliActor(env, args.request); if (!auth.ok) return auth.response; const parsed = await parseCliJsonBody<Record<string, unknown>>(args.request); if (!parsed.ok) return parsed.response; const { name, parentFolderId } = parsed.value; if (typeof name !== "string" || !name.trim() || name.trim().length > 48 || (parentFolderId !== undefined && (!Number.isInteger(parentFolderId) || (parentFolderId as number) <= 0))) return cliError("invalid_request", 400); const result = await createFolder(env.DB, { name: name.trim(), actor: viewer(auth), ...(typeof parentFolderId === "number" ? { parentFolderId } : {}) }); if (!result.ok) return cliError(result.reason === "duplicate" ? "conflict" : result.reason, result.reason === "duplicate" ? 409 : result.reason === "forbidden" ? 403 : 404); return cliJson({ folder: result.folder }, { status: 201 }); }
