import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("posts", "routes/posts.tsx"),
  route("schedule", "routes/schedule.tsx"),
  route("settings", "routes/settings.tsx"),
  route("settings/contributors", "routes/settings.contributors.tsx"),
  route("settings/x", "routes/settings.x.tsx"),
  route("settings/google-photos", "routes/settings.google-photos.ts"),
  route("api/posts", "routes/api.posts.ts"),
  route("api/contributor-candidates", "routes/api.contributor-candidates.ts"),
  route("api/media/:id", "routes/api.media.$id.ts"),
  route("api/cli/v1/posts", "routes/api.cli.v1.posts.ts"),
  route("api/cli/v1/posts/:id", "routes/api.cli.v1.posts.$id.ts"),
  route("api/cli/v1/posts/:id/media", "routes/api.cli.v1.posts.$id.media.ts"),
  route("api/cli/v1/posts/:id/publish", "routes/api.cli.v1.posts.$id.publish.ts"),
  route("api/cli/v1/media/:id", "routes/api.cli.v1.media.$id.ts"),
  route("api/cli/v1/contributors", "routes/api.cli.v1.contributors.ts"),
  route("api/cli/v1/x-accounts", "routes/api.cli.v1.x-accounts.ts"),
  route("api/cli/v1/x-accounts/:id", "routes/api.cli.v1.x-accounts.$id.ts"),
  route("api/google-photos-media/:id", "routes/api.google-photos-media.$id.ts"),
  route("api/google-photos-import/*", "routes/api.google-photos-import.$.ts"),
  route("api/chapter", "routes/api.chapter.ts"),
  route("x/connect", "routes/x.connect.ts"),
  route("x/callback", "routes/x.callback.ts"),
  route("google/photos/library", "routes/google.photos.library.tsx"),
  route("signin", "routes/signin.tsx"),
  route("no-chapter", "routes/no-chapter.tsx"),
  route("api/auth/*", "routes/api.auth.$.ts"),
  route("auth/signout", "routes/auth.signout.ts"),
] satisfies RouteConfig;
