#!/usr/bin/env bash
# dump-schema.sh — regenerate schema.sql for an app from its migrations/.
#
# Replays migrations/*.sql into a throwaway SQLite DB and writes the resulting
# `.schema` to ./schema.sql. Run from inside the app directory (this is how
# pnpm invokes package scripts), or pass the app dir as $1.
#
# Requires: sqlite3 (>= 3.x).

set -euo pipefail

app_dir="${1:-$PWD}"
app_dir="$(cd "$app_dir" && pwd)"
migrations_dir="$app_dir/migrations"
out="$app_dir/schema.sql"

if [ ! -d "$migrations_dir" ]; then
  echo "dump-schema: no migrations/ in $app_dir — skipping" >&2
  exit 0
fi

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "dump-schema: sqlite3 not found on PATH" >&2
  exit 1
fi

pkg_name="$(basename "$app_dir")"
if [ -f "$app_dir/package.json" ]; then
  parsed="$(node -p "require('$app_dir/package.json').name || ''" 2>/dev/null || true)"
  [ -n "$parsed" ] && pkg_name="$parsed"
fi

tmp_db="$(mktemp -t dump-schema.XXXXXX.db)"
trap 'rm -f "$tmp_db"' EXIT

shopt -s nullglob
migrations=( "$migrations_dir"/*.sql )
shopt -u nullglob

if [ ${#migrations[@]} -eq 0 ]; then
  echo "dump-schema: no .sql files in $migrations_dir — skipping" >&2
  exit 0
fi

for f in "${migrations[@]}"; do
  sqlite3 "$tmp_db" < "$f"
done

{
  echo "-- Schema dump for $pkg_name"
  echo "-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand."
  echo ""
  sqlite3 "$tmp_db" .schema | grep -v '^CREATE TABLE sqlite_sequence'
} > "$out"

echo "dump-schema: wrote $out"
