/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve an original or transformed public image */
        get: operations["getPublicImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local TinyURL integration upload endpoint */
        post: operations["internalUploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replace/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replaceImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadMobileImage"];
        delete: operations["deleteMobileImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slug/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set or clear an image's custom slug (dashboard session) */
        post: operations["setImageSlug"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCliImages"];
        put?: never;
        post: operations["createCliImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCliImage"];
        put: operations["replaceCliImage"];
        post?: never;
        delete: operations["deleteCliImage"];
        options?: never;
        head?: never;
        /** Set or clear an image's custom slug */
        patch: operations["updateCliImageSlug"];
        trace?: never;
    };
    "/api/cli/v1/images/{id}/mobile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadCliMobileImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImageId: {
            id: string;
        };
        UploadResult: {
            id: string;
            /** Format: uri */
            url: string;
        };
        Success: {
            /** @enum {boolean} */
            ok: true;
        };
        CliImage: {
            id: string;
            userId: string;
            accountId: string;
            chapterId: number;
            slug: string | null;
            r2Key: string;
            contentType: string;
            byteSize: number;
            width: number | null;
            height: number | null;
            filename: string | null;
            mobileR2Key: string | null;
            mobileContentType: string | null;
            mobileByteSize: number | null;
            mobileFilename: string | null;
            mobileUpdatedAt: number | null;
            createdAt: number;
            updatedAt: number;
        };
        CliImageList: {
            images: components["schemas"]["CliImage"][];
            nextCursor: string | null;
        };
        Error: {
            error: string;
        };
        CliImageResponse: {
            image: components["schemas"]["CliImage"];
        };
        CliReplaceResult: {
            id: string;
            /** Format: uri */
            url: string;
            updatedAt: number;
        };
        CliDeleteResult: {
            id: string;
            /** @enum {boolean} */
            deleted: true;
        };
        CliMobileResult: {
            id: string;
            updatedAt: number;
        };
        InternalUploadUser: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: uri */
            image: string | null;
            isAdmin: boolean;
        };
    };
    responses: {
        /** @description Image not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The authenticated user cannot modify this image. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The request is missing required fields or is malformed. */
        CliBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The bearer token is missing, invalid, or lacks the CLI scope. */
        CliUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller cannot act on this image or chapter. */
        CliForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The image exceeds 10 MiB. */
        CliTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Image not found. */
        CliNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested slug is already in use by another image. */
        CliConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        ImageIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPublicImage: {
        parameters: {
            query?: {
                w?: number;
                h?: number;
                q?: number;
                fit?: string;
                f?: "avif" | "webp" | "jpeg" | "png";
                variant?: "mobile";
            };
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Image file
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageId"];
                };
            };
            /** @description File is missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Image exceeds 10 MiB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File is not an image */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    internalUploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description JSON-encoded InternalUploadUser */
                    user: string;
                    chapterId: number;
                };
            };
        };
        responses: {
            /** @description Uploaded image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Invalid image owner */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Image exceeds 10 MiB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File is not an image */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Image replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageId"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadMobileImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Mobile image uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageId"];
                };
            };
        };
    };
    deleteMobileImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mobile image removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    setImageSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description New slug; an empty or absent value clears it. */
                    slug?: string;
                };
                "application/json": {
                    slug?: string | null;
                };
            };
        };
        responses: {
            /** @description Slug updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageId"];
                };
            };
            /** @description The slug is malformed or reserved. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The slug is already in use by another image. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    listCliImages: {
        parameters: {
            query?: {
                chapterId?: number;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's images */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliImageList"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    createCliImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Image file
                     */
                    file: string;
                    /** @description Required when the caller has more than one chapter membership. */
                    chapterId?: string;
                };
            };
        };
        responses: {
            /** @description Uploaded image */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            413: components["responses"]["CliTooLarge"];
        };
    };
    getCliImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image management metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliImageResponse"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
        };
    };
    replaceCliImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Image replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliReplaceResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
            413: components["responses"]["CliTooLarge"];
        };
    };
    deleteCliImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliDeleteResult"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
        };
    };
    updateCliImageSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description New slug, or null / empty string to clear it. */
                    slug: string | null;
                };
            };
        };
        responses: {
            /** @description Slug updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliImageResponse"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
        };
    };
    uploadCliMobileImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Mobile image uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliMobileResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
            404: components["responses"]["CliNotFound"];
            413: components["responses"]["CliTooLarge"];
        };
    };
}
