/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cli/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scheduled posts for a chapter */
        get: operations["listCliPosts"];
        put?: never;
        /** Create a scheduled post draft */
        post: operations["createCliPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a post and its ordered media */
        get: operations["getCliPost"];
        put?: never;
        post?: never;
        /**
         * Delete a post draft
         * @description Rejected with 409 when the post is already `posting` or `published` — a state conflict, not a malformed request.
         */
        delete: operations["deleteCliPost"];
        options?: never;
        head?: never;
        /** Update a post draft */
        patch: operations["updateCliPost"];
        trace?: never;
    };
    "/api/cli/v1/posts/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach an image to a post draft */
        post: operations["attachCliPostMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an image from its post
         * @description Removes a single `post_media` row (and its stored object) by media id. The media id is discovered from `GET /api/cli/v1/posts/{id}`, so a client can remove media attached by the dashboard or an earlier CLI session, not only media it uploaded itself.
         */
        delete: operations["deleteCliMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/contributors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a chapter's contributors (organizer only) */
        get: operations["listCliContributors"];
        put?: never;
        /** Grant a user contributor access to a chapter (organizer only) */
        post: operations["addCliContributor"];
        /**
         * Revoke a user's contributor access to a chapter (organizer only)
         * @description Contributor deletion is addressed by `chapterId` + `userEmail` query parameters, NOT a `/contributors/{id}` path. This is deliberate: the `sns_contributors` table has no single-column id — its primary key is the `(chapter_id, user_email)` pair — so there is no id to put in the path. This is the one resource in this API that does not follow the `/{id}` convention.
         */
        delete: operations["removeCliContributor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/x-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a chapter's usable X accounts
         * @description Returns only identity/metadata for the chapter's active (non-revoked) X accounts, so `xAccountId` is discoverable when creating a post. Encrypted token columns are never returned.
         */
        get: operations["listCliXAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/v1/x-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a chapter's X account
         * @description Soft-revokes the account (the row is kept because published posts still reference it). Requires an `xUserId` in the JSON body that exactly matches the account, matching the dashboard's revoke confirmation. Organizer or contributor access to the account's chapter is required.
         */
        delete: operations["revokeCliXAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PostStatus: "scheduled" | "waiting_for_photo" | "posting" | "published" | "failed" | "needs_confirmation";
        /** @enum {string} */
        PostCondition: "scheduled" | "photo_required";
        Post: {
            id: string;
            chapterId: number;
            xAccountId: string;
            text: string;
            scheduledAt: string;
            condition: components["schemas"]["PostCondition"];
            status: components["schemas"]["PostStatus"];
            createdByUserId: string;
            publishedXPostId: string | null;
            publishedAt: string | null;
            failureReason: string | null;
            linkPreviewUrl: string | null;
            linkPreviewTitle: string | null;
            linkPreviewDescription: string | null;
            linkPreviewImageUrl: string | null;
            createdAt: string;
            updatedAt: string;
        };
        PostList: {
            posts: components["schemas"]["Post"][];
            nextCursor: string | null;
        };
        Error: {
            error: string;
        };
        CreatePostRequest: {
            chapterId: number;
            xAccountId: string;
            text: string;
            scheduledAt: string;
            condition: components["schemas"]["PostCondition"];
            /** @description X handles to tag; normalized and resolved through the selected X account, maximum 10. */
            tagHandles?: string[];
        };
        PostResponse: {
            post: components["schemas"]["Post"];
        };
        PostMedia: {
            id: string;
            postId: string;
            r2Key: string;
            contentType: string;
            byteSize: number;
            altText: string;
            sortOrder: number;
            createdAt: string;
        };
        PostDetailResponse: {
            post: components["schemas"]["Post"];
            media: components["schemas"]["PostMedia"][];
        };
        PostDeleteResult: {
            id: string;
            /** @enum {boolean} */
            deleted: true;
        };
        /** @description Every field is optional; omitted fields are left unchanged. `linkPreview` is intentionally not accepted — preview metadata is always derived server-side from the final text. */
        UpdatePostRequest: {
            xAccountId?: string;
            text?: string;
            scheduledAt?: string;
            condition?: components["schemas"]["PostCondition"];
            tagHandles?: string[];
        };
        MediaAttachResult: {
            media: components["schemas"]["PostMedia"];
            post: components["schemas"]["Post"];
        };
        MediaDeleteResult: {
            id: string;
            /** @enum {boolean} */
            deleted: true;
            post: components["schemas"]["Post"];
        };
        Contributor: {
            /** Format: email */
            email: string;
            createdAt: string;
        };
        ContributorList: {
            contributors: components["schemas"]["Contributor"][];
            nextCursor: string | null;
        };
        AddContributorRequest: {
            chapterId: number;
            /** Format: email */
            userEmail: string;
        };
        AddContributorResult: {
            chapterId: number;
            /** Format: email */
            userEmail: string;
        };
        DeleteContributorResult: {
            /** @enum {boolean} */
            deleted: true;
        };
        XAccountSummary: {
            id: string;
            chapterId: number;
            xUserId: string;
            username: string;
            displayName: string;
            profileImageUrl: string | null;
            authorizedByUserId: string;
            createdAt: string;
            updatedAt: string;
            revokedAt: string | null;
        };
        XAccountList: {
            accounts: components["schemas"]["XAccountSummary"][];
        };
        RevokeXAccountRequest: {
            /** @description Must exactly match the account's current `xUserId`, to guard against an accidental revoke. */
            xUserId: string;
        };
        RevokeXAccountResult: {
            id: string;
            /** @enum {boolean} */
            revoked: true;
        };
    };
    responses: {
        /** @description The request is missing required fields or is malformed. */
        CliBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The bearer token is missing, invalid, or lacks the CLI scope. */
        CliUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller is not an organizer or contributor of this chapter. */
        CliForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist, or the caller cannot see it. Id-addressed routes deliberately return 404 (never 403) for a resource in another chapter, so a caller cannot enumerate ids across chapters. */
        CliNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the post's current state — for example editing, deleting, or attaching media to a post that is already `posting` or `published`. */
        CliConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An uploaded image exceeds 5 MiB. */
        CliPayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ChapterIdQuery: number;
        Limit: number;
        Cursor: string;
        ResourceIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCliPosts: {
        parameters: {
            query: {
                chapterId: components["parameters"]["ChapterIdQuery"];
                status?: components["schemas"]["PostStatus"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A bounded page of the chapter's posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostList"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    createCliPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description The created post. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    getCliPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post aggregate — the post plus its `sortOrder`-ordered media. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetailResponse"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
        };
    };
    deleteCliPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDeleteResult"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
        };
    };
    updateCliPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostRequest"];
            };
        };
        responses: {
            /** @description The updated post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
        };
    };
    attachCliPostMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Image file
                     */
                    file: string;
                    /** @description Zero-based position of this image within the post. */
                    sortOrder: string;
                    altText?: string;
                };
            };
        };
        responses: {
            /** @description The attached media plus the recomputed post. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAttachResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
            413: components["responses"]["CliPayloadTooLarge"];
        };
    };
    deleteCliMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The media was removed; the recomputed post is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDeleteResult"];
                };
            };
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
            409: components["responses"]["CliConflict"];
        };
    };
    listCliContributors: {
        parameters: {
            query: {
                chapterId: components["parameters"]["ChapterIdQuery"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A bounded page of the chapter's contributors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributorList"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    addCliContributor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddContributorRequest"];
            };
        };
        responses: {
            /** @description The contributor grant (idempotent — an existing grant is left untouched). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddContributorResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    removeCliContributor: {
        parameters: {
            query: {
                chapterId: components["parameters"]["ChapterIdQuery"];
                userEmail: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contributor grant was removed (idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteContributorResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    listCliXAccounts: {
        parameters: {
            query: {
                chapterId: components["parameters"]["ChapterIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chapter's usable X account summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XAccountList"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            403: components["responses"]["CliForbidden"];
        };
    };
    revokeCliXAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeXAccountRequest"];
            };
        };
        responses: {
            /** @description The account was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeXAccountResult"];
                };
            };
            400: components["responses"]["CliBadRequest"];
            401: components["responses"]["CliUnauthorized"];
            404: components["responses"]["CliNotFound"];
        };
    };
}
