import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/images/gallery.tsx"),
  route("i/:id", "routes/images/detail.tsx"),
  route("api/upload", "routes/api/images/upload.ts"),
  route("api/internal/upload", "routes/api/images/internal-upload.ts"),
  route("api/replace/:id", "routes/api/images/replace.ts"),
  route("api/mobile/:id", "routes/api/images/mobile.ts"),
  route("api/slug/:id", "routes/api/images/slug.ts"),
  route("api/move/:id", "routes/api/images/move.ts"),
  route("api/share/:id", "routes/api/images/share.ts"),
  route("api/delete/:id", "routes/api/images/delete.ts"),
  route("api/folders", "routes/api/folders/list.ts"),
  route("api/folders/:id", "routes/api/folders/folder.ts"),
  route("api/cli/v1/images", "routes/api/cli/images/list.ts"),
  route("api/cli/v1/images/:id", "routes/api/cli/images/image.ts"),
  route("api/cli/v1/images/:id/mobile", "routes/api/cli/images/mobile.ts"),
  route("api/cli/v1/folders", "routes/api/cli/folders/list.ts"),
  route("api/cli/v1/folders/:id", "routes/api/cli/folders/folder.ts"),
  route("api/auth/*", "routes/auth/handler.ts"),
  route("auth/signout", "routes/auth/signout.ts"),
  route("signin", "routes/auth/signin.tsx"),
  route("no-chapter", "routes/auth/no-chapter.tsx"),
  route(":id", "routes/images/serve.tsx"),
] satisfies RouteConfig;
