import { jsx } from "react/jsx-runtime";
import { Icons } from "./Icons";
const meta = {
  title: "Components/Icons",
  component: Icons,
  parameters: { layout: "centered" },
  args: { name: "Heart", size: 24, "aria-label": "\u304A\u6C17\u306B\u5165\u308A" },
};
const Icons_stories_default = meta;
const Default = {};
const Static = {
  args: {
    name: "AlertCircle",
    animateOnHover: false,
    strokeWidth: 1.5,
    style: { color: "var(--gdg-danger)" },
  },
  render: (args) => /* @__PURE__ */ jsx(Icons, { ...args, "data-testid": "static-icon" }),
};
const Decorative = { args: { name: "Sparkles", "aria-hidden": true } };
const wikiIconNames = [
  "AlertCircle",
  "AlertTriangle",
  "Archive",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUpRight",
  "Bell",
  "BellDot",
  "BellOff",
  "CalendarDays",
  "ChartPie",
  "Check",
  "CheckCircle2",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "Clipboard",
  "Clock",
  "Copy",
  "ExternalLink",
  "FileInput",
  "FileQuestion",
  "FileText",
  "Folder",
  "FolderOpen",
  "Globe",
  "Globe2",
  "Hash",
  "History",
  "Home",
  "LayoutList",
  "Link",
  "Link2",
  "List",
  "ListChecks",
  "ListFilter",
  "ListTodo",
  "Loader2",
  "LoaderCircle",
  "LockKeyhole",
  "MessageSquare",
  "Moon",
  "MoreHorizontal",
  "MoveHorizontal",
  "PanelLeft",
  "PanelLeftClose",
  "Pencil",
  "Plus",
  "RefreshCw",
  "RotateCcw",
  "Send",
  "ServerCrash",
  "Settings",
  "Share2",
  "Smile",
  "Star",
  "Sun",
  "Tag",
  "Trash2",
  "Type",
  "Upload",
  "UserRound",
  "UsersRound",
  "X",
];
const WikiCatalog = {
  render: () =>
    /* @__PURE__ */ jsx("div", {
      style: { display: "flex", flexWrap: "wrap", gap: 16, maxWidth: 640 },
      children: wikiIconNames.map((name) =>
        /* @__PURE__ */ jsx(Icons, { name, "aria-hidden": "true", size: 20 }, name),
      ),
    }),
};
export { Decorative, Default, Static, WikiCatalog, Icons_stories_default as default };
