import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("i/:id", "routes/i.$id.tsx"),
  route("api/upload", "routes/api.upload.ts"),
  route("api/internal/upload", "routes/api.internal-upload.ts"),
  route("api/replace/:id", "routes/api.replace.$id.ts"),
  route("api/mobile/:id", "routes/api.mobile.$id.ts"),
  route("api/slug/:id", "routes/api.slug.$id.ts"),
  route("api/move/:id", "routes/api.move.$id.ts"),
  route("api/share/:id", "routes/api.share.$id.ts"),
  route("api/delete/:id", "routes/api.delete.$id.ts"),
  route("api/folders", "routes/api.folders.ts"),
  route("api/folders/:id", "routes/api.folders.$id.ts"),
  route("api/cli/v1/images", "routes/api.cli.v1.images.ts"),
  route("api/cli/v1/images/:id", "routes/api.cli.v1.images.$id.ts"),
  route("api/cli/v1/images/:id/mobile", "routes/api.cli.v1.images.$id.mobile.ts"),
  route("api/cli/v1/folders", "routes/api.cli.v1.folders.ts"),
  route("api/cli/v1/folders/:id", "routes/api.cli.v1.folders.$id.ts"),
  route("api/auth/*", "routes/api.auth.$.ts"),
  route("auth/signout", "routes/auth.signout.ts"),
  route("signin", "routes/signin.tsx"),
  route("no-chapter", "routes/no-chapter.tsx"),
  route(":id", "routes/$id.tsx"),
] satisfies RouteConfig;
