-- Schema dump for @gdgjp/img
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE images (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  account_id    TEXT NOT NULL,
  chapter_id    INTEGER NOT NULL,
  r2_key        TEXT NOT NULL,
  content_type  TEXT NOT NULL,
  byte_size     INTEGER NOT NULL,
  width         INTEGER,
  height        INTEGER,
  filename      TEXT,
  created_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at    INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX idx_images_user ON images(user_id, created_at DESC);
CREATE INDEX idx_images_chapter ON images(chapter_id, created_at DESC);
CREATE TABLE IF NOT EXISTS "user" (
  id           TEXT PRIMARY KEY,
  email        TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  image        TEXT,
  is_admin     INTEGER NOT NULL DEFAULT 0,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at   INTEGER NOT NULL DEFAULT (unixepoch())
);
